-- Create "benefits" table
CREATE TABLE "benefits" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "title" character varying NOT NULL, "description" text NOT NULL, "display_order" bigint NOT NULL DEFAULT 0, PRIMARY KEY ("id"));
-- Create "faq_items" table
CREATE TABLE "faq_items" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "question" character varying NOT NULL, "answer" text NOT NULL, "display_order" bigint NOT NULL DEFAULT 0, PRIMARY KEY ("id"));
-- Create "pain_points" table
CREATE TABLE "pain_points" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "title" character varying NOT NULL, "description" text NOT NULL, "display_order" bigint NOT NULL DEFAULT 0, PRIMARY KEY ("id"));
-- Create "pricings" table
CREATE TABLE "pricings" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "rate" character varying NOT NULL, "billing_hours" character varying NOT NULL, "trial_rate" character varying NOT NULL, "trial_note" character varying NOT NULL, PRIMARY KEY ("id"));
-- Create "requirements" table
CREATE TABLE "requirements" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "kind" character varying NOT NULL, "text" text NOT NULL, "display_order" bigint NOT NULL DEFAULT 0, PRIMARY KEY ("id"));
-- Create "work_conditions" table
CREATE TABLE "work_conditions" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "label" character varying NOT NULL, "value" character varying NOT NULL, "display_order" bigint NOT NULL DEFAULT 0, PRIMARY KEY ("id"));
-- Create "pricing_patterns" table
CREATE TABLE "pricing_patterns" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "label" character varying NOT NULL, "trial_flex" bigint NOT NULL, "trial_period" character varying NOT NULL, "regular_flex" bigint NOT NULL, "regular_period" character varying NOT NULL, "display_order" bigint NOT NULL DEFAULT 0, "pricing_id" bigint NULL, PRIMARY KEY ("id"), CONSTRAINT "pricing_patterns_pricings_patterns" FOREIGN KEY ("pricing_id") REFERENCES "pricings" ("id") ON UPDATE NO ACTION ON DELETE SET NULL);
-- Create "phases" table
CREATE TABLE "phases" ("id" character varying NOT NULL, "label" character varying NOT NULL, "display_order" bigint NOT NULL DEFAULT 0, PRIMARY KEY ("id"));
-- Create "projects" table
CREATE TABLE "projects" ("id" character varying NOT NULL, "title" character varying NOT NULL, "period_start" date NOT NULL, "period_end" date NULL, "team" character varying NOT NULL, "role" character varying NOT NULL, "summary" text NOT NULL, PRIMARY KEY ("id"));
-- Create "project_phases" table
CREATE TABLE "project_phases" ("project_id" character varying NOT NULL, "phase_id" character varying NOT NULL, PRIMARY KEY ("project_id", "phase_id"), CONSTRAINT "project_phases_phase_id" FOREIGN KEY ("phase_id") REFERENCES "phases" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "project_phases_project_id" FOREIGN KEY ("project_id") REFERENCES "projects" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- Create "techs" table
CREATE TABLE "techs" ("id" character varying NOT NULL, "label" character varying NOT NULL, "category" character varying NOT NULL, "display_order" bigint NOT NULL DEFAULT 0, PRIMARY KEY ("id"));
-- Create "project_techs" table
CREATE TABLE "project_techs" ("project_id" character varying NOT NULL, "tech_id" character varying NOT NULL, PRIMARY KEY ("project_id", "tech_id"), CONSTRAINT "project_techs_project_id" FOREIGN KEY ("project_id") REFERENCES "projects" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "project_techs_tech_id" FOREIGN KEY ("tech_id") REFERENCES "techs" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
