// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// BenefitsColumns holds the columns for the "benefits" table.
	BenefitsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "title", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Size: 2147483647},
		{Name: "display_order", Type: field.TypeInt, Default: 0},
	}
	// BenefitsTable holds the schema information for the "benefits" table.
	BenefitsTable = &schema.Table{
		Name:       "benefits",
		Columns:    BenefitsColumns,
		PrimaryKey: []*schema.Column{BenefitsColumns[0]},
	}
	// FaqItemsColumns holds the columns for the "faq_items" table.
	FaqItemsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "question", Type: field.TypeString},
		{Name: "answer", Type: field.TypeString, Size: 2147483647},
		{Name: "display_order", Type: field.TypeInt, Default: 0},
	}
	// FaqItemsTable holds the schema information for the "faq_items" table.
	FaqItemsTable = &schema.Table{
		Name:       "faq_items",
		Columns:    FaqItemsColumns,
		PrimaryKey: []*schema.Column{FaqItemsColumns[0]},
	}
	// PainPointsColumns holds the columns for the "pain_points" table.
	PainPointsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "title", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Size: 2147483647},
		{Name: "display_order", Type: field.TypeInt, Default: 0},
	}
	// PainPointsTable holds the schema information for the "pain_points" table.
	PainPointsTable = &schema.Table{
		Name:       "pain_points",
		Columns:    PainPointsColumns,
		PrimaryKey: []*schema.Column{PainPointsColumns[0]},
	}
	// PhasesColumns holds the columns for the "phases" table.
	PhasesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "label", Type: field.TypeString},
		{Name: "display_order", Type: field.TypeInt, Default: 0},
	}
	// PhasesTable holds the schema information for the "phases" table.
	PhasesTable = &schema.Table{
		Name:       "phases",
		Columns:    PhasesColumns,
		PrimaryKey: []*schema.Column{PhasesColumns[0]},
	}
	// PricingsColumns holds the columns for the "pricings" table.
	PricingsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "rate", Type: field.TypeString},
		{Name: "billing_hours", Type: field.TypeString},
		{Name: "trial_rate", Type: field.TypeString},
		{Name: "trial_note", Type: field.TypeString},
	}
	// PricingsTable holds the schema information for the "pricings" table.
	PricingsTable = &schema.Table{
		Name:       "pricings",
		Columns:    PricingsColumns,
		PrimaryKey: []*schema.Column{PricingsColumns[0]},
	}
	// PricingPatternsColumns holds the columns for the "pricing_patterns" table.
	PricingPatternsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "label", Type: field.TypeString},
		{Name: "trial_flex", Type: field.TypeInt},
		{Name: "trial_period", Type: field.TypeString},
		{Name: "regular_flex", Type: field.TypeInt},
		{Name: "regular_period", Type: field.TypeString},
		{Name: "display_order", Type: field.TypeInt, Default: 0},
		{Name: "pricing_id", Type: field.TypeInt, Nullable: true},
	}
	// PricingPatternsTable holds the schema information for the "pricing_patterns" table.
	PricingPatternsTable = &schema.Table{
		Name:       "pricing_patterns",
		Columns:    PricingPatternsColumns,
		PrimaryKey: []*schema.Column{PricingPatternsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "pricing_patterns_pricings_patterns",
				Columns:    []*schema.Column{PricingPatternsColumns[7]},
				RefColumns: []*schema.Column{PricingsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// ProjectsColumns holds the columns for the "projects" table.
	ProjectsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "title", Type: field.TypeString},
		{Name: "period_start", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "date"}},
		{Name: "period_end", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "date"}},
		{Name: "team", Type: field.TypeString},
		{Name: "role", Type: field.TypeString},
		{Name: "summary", Type: field.TypeString, Size: 2147483647},
	}
	// ProjectsTable holds the schema information for the "projects" table.
	ProjectsTable = &schema.Table{
		Name:       "projects",
		Columns:    ProjectsColumns,
		PrimaryKey: []*schema.Column{ProjectsColumns[0]},
	}
	// RequirementsColumns holds the columns for the "requirements" table.
	RequirementsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "kind", Type: field.TypeEnum, Enums: []string{"must_have", "nice_to_have"}},
		{Name: "text", Type: field.TypeString, Size: 2147483647},
		{Name: "display_order", Type: field.TypeInt, Default: 0},
	}
	// RequirementsTable holds the schema information for the "requirements" table.
	RequirementsTable = &schema.Table{
		Name:       "requirements",
		Columns:    RequirementsColumns,
		PrimaryKey: []*schema.Column{RequirementsColumns[0]},
	}
	// TechsColumns holds the columns for the "techs" table.
	TechsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "label", Type: field.TypeString},
		{Name: "category", Type: field.TypeString},
		{Name: "display_order", Type: field.TypeInt, Default: 0},
	}
	// TechsTable holds the schema information for the "techs" table.
	TechsTable = &schema.Table{
		Name:       "techs",
		Columns:    TechsColumns,
		PrimaryKey: []*schema.Column{TechsColumns[0]},
	}
	// WorkConditionsColumns holds the columns for the "work_conditions" table.
	WorkConditionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "label", Type: field.TypeString},
		{Name: "value", Type: field.TypeString},
		{Name: "display_order", Type: field.TypeInt, Default: 0},
	}
	// WorkConditionsTable holds the schema information for the "work_conditions" table.
	WorkConditionsTable = &schema.Table{
		Name:       "work_conditions",
		Columns:    WorkConditionsColumns,
		PrimaryKey: []*schema.Column{WorkConditionsColumns[0]},
	}
	// ProjectTechsColumns holds the columns for the "project_techs" table.
	ProjectTechsColumns = []*schema.Column{
		{Name: "project_id", Type: field.TypeString},
		{Name: "tech_id", Type: field.TypeString},
	}
	// ProjectTechsTable holds the schema information for the "project_techs" table.
	ProjectTechsTable = &schema.Table{
		Name:       "project_techs",
		Columns:    ProjectTechsColumns,
		PrimaryKey: []*schema.Column{ProjectTechsColumns[0], ProjectTechsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "project_techs_project_id",
				Columns:    []*schema.Column{ProjectTechsColumns[0]},
				RefColumns: []*schema.Column{ProjectsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "project_techs_tech_id",
				Columns:    []*schema.Column{ProjectTechsColumns[1]},
				RefColumns: []*schema.Column{TechsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// ProjectPhasesColumns holds the columns for the "project_phases" table.
	ProjectPhasesColumns = []*schema.Column{
		{Name: "project_id", Type: field.TypeString},
		{Name: "phase_id", Type: field.TypeString},
	}
	// ProjectPhasesTable holds the schema information for the "project_phases" table.
	ProjectPhasesTable = &schema.Table{
		Name:       "project_phases",
		Columns:    ProjectPhasesColumns,
		PrimaryKey: []*schema.Column{ProjectPhasesColumns[0], ProjectPhasesColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "project_phases_project_id",
				Columns:    []*schema.Column{ProjectPhasesColumns[0]},
				RefColumns: []*schema.Column{ProjectsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "project_phases_phase_id",
				Columns:    []*schema.Column{ProjectPhasesColumns[1]},
				RefColumns: []*schema.Column{PhasesColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		BenefitsTable,
		FaqItemsTable,
		PainPointsTable,
		PhasesTable,
		PricingsTable,
		PricingPatternsTable,
		ProjectsTable,
		RequirementsTable,
		TechsTable,
		WorkConditionsTable,
		ProjectTechsTable,
		ProjectPhasesTable,
	}
)

func init() {
	PricingPatternsTable.ForeignKeys[0].RefTable = PricingsTable
	TechsTable.Annotation = &entsql.Annotation{
		Table: "techs",
	}
	ProjectTechsTable.ForeignKeys[0].RefTable = ProjectsTable
	ProjectTechsTable.ForeignKeys[1].RefTable = TechsTable
	ProjectPhasesTable.ForeignKeys[0].RefTable = ProjectsTable
	ProjectPhasesTable.ForeignKeys[1].RefTable = PhasesTable
}
