// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/hashiguchip/resume_2026/apps/api/ent/benefit"
	"github.com/hashiguchip/resume_2026/apps/api/ent/predicate"
)

// BenefitUpdate is the builder for updating Benefit entities.
type BenefitUpdate struct {
	config
	hooks    []Hook
	mutation *BenefitMutation
}

// Where appends a list predicates to the BenefitUpdate builder.
func (_u *BenefitUpdate) Where(ps ...predicate.Benefit) *BenefitUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTitle sets the "title" field.
func (_u *BenefitUpdate) SetTitle(v string) *BenefitUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *BenefitUpdate) SetNillableTitle(v *string) *BenefitUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *BenefitUpdate) SetDescription(v string) *BenefitUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *BenefitUpdate) SetNillableDescription(v *string) *BenefitUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetDisplayOrder sets the "display_order" field.
func (_u *BenefitUpdate) SetDisplayOrder(v int) *BenefitUpdate {
	_u.mutation.ResetDisplayOrder()
	_u.mutation.SetDisplayOrder(v)
	return _u
}

// SetNillableDisplayOrder sets the "display_order" field if the given value is not nil.
func (_u *BenefitUpdate) SetNillableDisplayOrder(v *int) *BenefitUpdate {
	if v != nil {
		_u.SetDisplayOrder(*v)
	}
	return _u
}

// AddDisplayOrder adds value to the "display_order" field.
func (_u *BenefitUpdate) AddDisplayOrder(v int) *BenefitUpdate {
	_u.mutation.AddDisplayOrder(v)
	return _u
}

// Mutation returns the BenefitMutation object of the builder.
func (_u *BenefitUpdate) Mutation() *BenefitMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *BenefitUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BenefitUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *BenefitUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BenefitUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BenefitUpdate) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := benefit.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Benefit.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := benefit.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "Benefit.description": %w`, err)}
		}
	}
	return nil
}

func (_u *BenefitUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(benefit.Table, benefit.Columns, sqlgraph.NewFieldSpec(benefit.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(benefit.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(benefit.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.DisplayOrder(); ok {
		_spec.SetField(benefit.FieldDisplayOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDisplayOrder(); ok {
		_spec.AddField(benefit.FieldDisplayOrder, field.TypeInt, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{benefit.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// BenefitUpdateOne is the builder for updating a single Benefit entity.
type BenefitUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BenefitMutation
}

// SetTitle sets the "title" field.
func (_u *BenefitUpdateOne) SetTitle(v string) *BenefitUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *BenefitUpdateOne) SetNillableTitle(v *string) *BenefitUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *BenefitUpdateOne) SetDescription(v string) *BenefitUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *BenefitUpdateOne) SetNillableDescription(v *string) *BenefitUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetDisplayOrder sets the "display_order" field.
func (_u *BenefitUpdateOne) SetDisplayOrder(v int) *BenefitUpdateOne {
	_u.mutation.ResetDisplayOrder()
	_u.mutation.SetDisplayOrder(v)
	return _u
}

// SetNillableDisplayOrder sets the "display_order" field if the given value is not nil.
func (_u *BenefitUpdateOne) SetNillableDisplayOrder(v *int) *BenefitUpdateOne {
	if v != nil {
		_u.SetDisplayOrder(*v)
	}
	return _u
}

// AddDisplayOrder adds value to the "display_order" field.
func (_u *BenefitUpdateOne) AddDisplayOrder(v int) *BenefitUpdateOne {
	_u.mutation.AddDisplayOrder(v)
	return _u
}

// Mutation returns the BenefitMutation object of the builder.
func (_u *BenefitUpdateOne) Mutation() *BenefitMutation {
	return _u.mutation
}

// Where appends a list predicates to the BenefitUpdate builder.
func (_u *BenefitUpdateOne) Where(ps ...predicate.Benefit) *BenefitUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *BenefitUpdateOne) Select(field string, fields ...string) *BenefitUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Benefit entity.
func (_u *BenefitUpdateOne) Save(ctx context.Context) (*Benefit, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BenefitUpdateOne) SaveX(ctx context.Context) *Benefit {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *BenefitUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BenefitUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BenefitUpdateOne) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := benefit.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Benefit.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := benefit.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "Benefit.description": %w`, err)}
		}
	}
	return nil
}

func (_u *BenefitUpdateOne) sqlSave(ctx context.Context) (_node *Benefit, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(benefit.Table, benefit.Columns, sqlgraph.NewFieldSpec(benefit.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Benefit.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, benefit.FieldID)
		for _, f := range fields {
			if !benefit.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != benefit.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(benefit.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(benefit.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.DisplayOrder(); ok {
		_spec.SetField(benefit.FieldDisplayOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDisplayOrder(); ok {
		_spec.AddField(benefit.FieldDisplayOrder, field.TypeInt, value)
	}
	_node = &Benefit{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{benefit.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
