// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/hashiguchip/resume_2026/apps/api/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/hashiguchip/resume_2026/apps/api/ent/benefit"
	"github.com/hashiguchip/resume_2026/apps/api/ent/faqitem"
	"github.com/hashiguchip/resume_2026/apps/api/ent/painpoint"
	"github.com/hashiguchip/resume_2026/apps/api/ent/phase"
	"github.com/hashiguchip/resume_2026/apps/api/ent/pricing"
	"github.com/hashiguchip/resume_2026/apps/api/ent/pricingpattern"
	"github.com/hashiguchip/resume_2026/apps/api/ent/project"
	"github.com/hashiguchip/resume_2026/apps/api/ent/requirement"
	"github.com/hashiguchip/resume_2026/apps/api/ent/tech"
	"github.com/hashiguchip/resume_2026/apps/api/ent/workcondition"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Benefit is the client for interacting with the Benefit builders.
	Benefit *BenefitClient
	// FAQItem is the client for interacting with the FAQItem builders.
	FAQItem *FAQItemClient
	// PainPoint is the client for interacting with the PainPoint builders.
	PainPoint *PainPointClient
	// Phase is the client for interacting with the Phase builders.
	Phase *PhaseClient
	// Pricing is the client for interacting with the Pricing builders.
	Pricing *PricingClient
	// PricingPattern is the client for interacting with the PricingPattern builders.
	PricingPattern *PricingPatternClient
	// Project is the client for interacting with the Project builders.
	Project *ProjectClient
	// Requirement is the client for interacting with the Requirement builders.
	Requirement *RequirementClient
	// Tech is the client for interacting with the Tech builders.
	Tech *TechClient
	// WorkCondition is the client for interacting with the WorkCondition builders.
	WorkCondition *WorkConditionClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Benefit = NewBenefitClient(c.config)
	c.FAQItem = NewFAQItemClient(c.config)
	c.PainPoint = NewPainPointClient(c.config)
	c.Phase = NewPhaseClient(c.config)
	c.Pricing = NewPricingClient(c.config)
	c.PricingPattern = NewPricingPatternClient(c.config)
	c.Project = NewProjectClient(c.config)
	c.Requirement = NewRequirementClient(c.config)
	c.Tech = NewTechClient(c.config)
	c.WorkCondition = NewWorkConditionClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:            ctx,
		config:         cfg,
		Benefit:        NewBenefitClient(cfg),
		FAQItem:        NewFAQItemClient(cfg),
		PainPoint:      NewPainPointClient(cfg),
		Phase:          NewPhaseClient(cfg),
		Pricing:        NewPricingClient(cfg),
		PricingPattern: NewPricingPatternClient(cfg),
		Project:        NewProjectClient(cfg),
		Requirement:    NewRequirementClient(cfg),
		Tech:           NewTechClient(cfg),
		WorkCondition:  NewWorkConditionClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:            ctx,
		config:         cfg,
		Benefit:        NewBenefitClient(cfg),
		FAQItem:        NewFAQItemClient(cfg),
		PainPoint:      NewPainPointClient(cfg),
		Phase:          NewPhaseClient(cfg),
		Pricing:        NewPricingClient(cfg),
		PricingPattern: NewPricingPatternClient(cfg),
		Project:        NewProjectClient(cfg),
		Requirement:    NewRequirementClient(cfg),
		Tech:           NewTechClient(cfg),
		WorkCondition:  NewWorkConditionClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Benefit.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	for _, n := range []interface{ Use(...Hook) }{
		c.Benefit, c.FAQItem, c.PainPoint, c.Phase, c.Pricing, c.PricingPattern,
		c.Project, c.Requirement, c.Tech, c.WorkCondition,
	} {
		n.Use(hooks...)
	}
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	for _, n := range []interface{ Intercept(...Interceptor) }{
		c.Benefit, c.FAQItem, c.PainPoint, c.Phase, c.Pricing, c.PricingPattern,
		c.Project, c.Requirement, c.Tech, c.WorkCondition,
	} {
		n.Intercept(interceptors...)
	}
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *BenefitMutation:
		return c.Benefit.mutate(ctx, m)
	case *FAQItemMutation:
		return c.FAQItem.mutate(ctx, m)
	case *PainPointMutation:
		return c.PainPoint.mutate(ctx, m)
	case *PhaseMutation:
		return c.Phase.mutate(ctx, m)
	case *PricingMutation:
		return c.Pricing.mutate(ctx, m)
	case *PricingPatternMutation:
		return c.PricingPattern.mutate(ctx, m)
	case *ProjectMutation:
		return c.Project.mutate(ctx, m)
	case *RequirementMutation:
		return c.Requirement.mutate(ctx, m)
	case *TechMutation:
		return c.Tech.mutate(ctx, m)
	case *WorkConditionMutation:
		return c.WorkCondition.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// BenefitClient is a client for the Benefit schema.
type BenefitClient struct {
	config
}

// NewBenefitClient returns a client for the Benefit from the given config.
func NewBenefitClient(c config) *BenefitClient {
	return &BenefitClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `benefit.Hooks(f(g(h())))`.
func (c *BenefitClient) Use(hooks ...Hook) {
	c.hooks.Benefit = append(c.hooks.Benefit, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `benefit.Intercept(f(g(h())))`.
func (c *BenefitClient) Intercept(interceptors ...Interceptor) {
	c.inters.Benefit = append(c.inters.Benefit, interceptors...)
}

// Create returns a builder for creating a Benefit entity.
func (c *BenefitClient) Create() *BenefitCreate {
	mutation := newBenefitMutation(c.config, OpCreate)
	return &BenefitCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Benefit entities.
func (c *BenefitClient) CreateBulk(builders ...*BenefitCreate) *BenefitCreateBulk {
	return &BenefitCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *BenefitClient) MapCreateBulk(slice any, setFunc func(*BenefitCreate, int)) *BenefitCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &BenefitCreateBulk{err: fmt.Errorf("calling to BenefitClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*BenefitCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &BenefitCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Benefit.
func (c *BenefitClient) Update() *BenefitUpdate {
	mutation := newBenefitMutation(c.config, OpUpdate)
	return &BenefitUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *BenefitClient) UpdateOne(_m *Benefit) *BenefitUpdateOne {
	mutation := newBenefitMutation(c.config, OpUpdateOne, withBenefit(_m))
	return &BenefitUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *BenefitClient) UpdateOneID(id int) *BenefitUpdateOne {
	mutation := newBenefitMutation(c.config, OpUpdateOne, withBenefitID(id))
	return &BenefitUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Benefit.
func (c *BenefitClient) Delete() *BenefitDelete {
	mutation := newBenefitMutation(c.config, OpDelete)
	return &BenefitDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *BenefitClient) DeleteOne(_m *Benefit) *BenefitDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *BenefitClient) DeleteOneID(id int) *BenefitDeleteOne {
	builder := c.Delete().Where(benefit.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &BenefitDeleteOne{builder}
}

// Query returns a query builder for Benefit.
func (c *BenefitClient) Query() *BenefitQuery {
	return &BenefitQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeBenefit},
		inters: c.Interceptors(),
	}
}

// Get returns a Benefit entity by its id.
func (c *BenefitClient) Get(ctx context.Context, id int) (*Benefit, error) {
	return c.Query().Where(benefit.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *BenefitClient) GetX(ctx context.Context, id int) *Benefit {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *BenefitClient) Hooks() []Hook {
	return c.hooks.Benefit
}

// Interceptors returns the client interceptors.
func (c *BenefitClient) Interceptors() []Interceptor {
	return c.inters.Benefit
}

func (c *BenefitClient) mutate(ctx context.Context, m *BenefitMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&BenefitCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&BenefitUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&BenefitUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&BenefitDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Benefit mutation op: %q", m.Op())
	}
}

// FAQItemClient is a client for the FAQItem schema.
type FAQItemClient struct {
	config
}

// NewFAQItemClient returns a client for the FAQItem from the given config.
func NewFAQItemClient(c config) *FAQItemClient {
	return &FAQItemClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `faqitem.Hooks(f(g(h())))`.
func (c *FAQItemClient) Use(hooks ...Hook) {
	c.hooks.FAQItem = append(c.hooks.FAQItem, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `faqitem.Intercept(f(g(h())))`.
func (c *FAQItemClient) Intercept(interceptors ...Interceptor) {
	c.inters.FAQItem = append(c.inters.FAQItem, interceptors...)
}

// Create returns a builder for creating a FAQItem entity.
func (c *FAQItemClient) Create() *FAQItemCreate {
	mutation := newFAQItemMutation(c.config, OpCreate)
	return &FAQItemCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of FAQItem entities.
func (c *FAQItemClient) CreateBulk(builders ...*FAQItemCreate) *FAQItemCreateBulk {
	return &FAQItemCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *FAQItemClient) MapCreateBulk(slice any, setFunc func(*FAQItemCreate, int)) *FAQItemCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &FAQItemCreateBulk{err: fmt.Errorf("calling to FAQItemClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*FAQItemCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &FAQItemCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for FAQItem.
func (c *FAQItemClient) Update() *FAQItemUpdate {
	mutation := newFAQItemMutation(c.config, OpUpdate)
	return &FAQItemUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *FAQItemClient) UpdateOne(_m *FAQItem) *FAQItemUpdateOne {
	mutation := newFAQItemMutation(c.config, OpUpdateOne, withFAQItem(_m))
	return &FAQItemUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *FAQItemClient) UpdateOneID(id int) *FAQItemUpdateOne {
	mutation := newFAQItemMutation(c.config, OpUpdateOne, withFAQItemID(id))
	return &FAQItemUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for FAQItem.
func (c *FAQItemClient) Delete() *FAQItemDelete {
	mutation := newFAQItemMutation(c.config, OpDelete)
	return &FAQItemDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *FAQItemClient) DeleteOne(_m *FAQItem) *FAQItemDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *FAQItemClient) DeleteOneID(id int) *FAQItemDeleteOne {
	builder := c.Delete().Where(faqitem.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &FAQItemDeleteOne{builder}
}

// Query returns a query builder for FAQItem.
func (c *FAQItemClient) Query() *FAQItemQuery {
	return &FAQItemQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeFAQItem},
		inters: c.Interceptors(),
	}
}

// Get returns a FAQItem entity by its id.
func (c *FAQItemClient) Get(ctx context.Context, id int) (*FAQItem, error) {
	return c.Query().Where(faqitem.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *FAQItemClient) GetX(ctx context.Context, id int) *FAQItem {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *FAQItemClient) Hooks() []Hook {
	return c.hooks.FAQItem
}

// Interceptors returns the client interceptors.
func (c *FAQItemClient) Interceptors() []Interceptor {
	return c.inters.FAQItem
}

func (c *FAQItemClient) mutate(ctx context.Context, m *FAQItemMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&FAQItemCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&FAQItemUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&FAQItemUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&FAQItemDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown FAQItem mutation op: %q", m.Op())
	}
}

// PainPointClient is a client for the PainPoint schema.
type PainPointClient struct {
	config
}

// NewPainPointClient returns a client for the PainPoint from the given config.
func NewPainPointClient(c config) *PainPointClient {
	return &PainPointClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `painpoint.Hooks(f(g(h())))`.
func (c *PainPointClient) Use(hooks ...Hook) {
	c.hooks.PainPoint = append(c.hooks.PainPoint, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `painpoint.Intercept(f(g(h())))`.
func (c *PainPointClient) Intercept(interceptors ...Interceptor) {
	c.inters.PainPoint = append(c.inters.PainPoint, interceptors...)
}

// Create returns a builder for creating a PainPoint entity.
func (c *PainPointClient) Create() *PainPointCreate {
	mutation := newPainPointMutation(c.config, OpCreate)
	return &PainPointCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of PainPoint entities.
func (c *PainPointClient) CreateBulk(builders ...*PainPointCreate) *PainPointCreateBulk {
	return &PainPointCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *PainPointClient) MapCreateBulk(slice any, setFunc func(*PainPointCreate, int)) *PainPointCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &PainPointCreateBulk{err: fmt.Errorf("calling to PainPointClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*PainPointCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &PainPointCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for PainPoint.
func (c *PainPointClient) Update() *PainPointUpdate {
	mutation := newPainPointMutation(c.config, OpUpdate)
	return &PainPointUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *PainPointClient) UpdateOne(_m *PainPoint) *PainPointUpdateOne {
	mutation := newPainPointMutation(c.config, OpUpdateOne, withPainPoint(_m))
	return &PainPointUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *PainPointClient) UpdateOneID(id int) *PainPointUpdateOne {
	mutation := newPainPointMutation(c.config, OpUpdateOne, withPainPointID(id))
	return &PainPointUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for PainPoint.
func (c *PainPointClient) Delete() *PainPointDelete {
	mutation := newPainPointMutation(c.config, OpDelete)
	return &PainPointDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *PainPointClient) DeleteOne(_m *PainPoint) *PainPointDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *PainPointClient) DeleteOneID(id int) *PainPointDeleteOne {
	builder := c.Delete().Where(painpoint.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &PainPointDeleteOne{builder}
}

// Query returns a query builder for PainPoint.
func (c *PainPointClient) Query() *PainPointQuery {
	return &PainPointQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypePainPoint},
		inters: c.Interceptors(),
	}
}

// Get returns a PainPoint entity by its id.
func (c *PainPointClient) Get(ctx context.Context, id int) (*PainPoint, error) {
	return c.Query().Where(painpoint.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *PainPointClient) GetX(ctx context.Context, id int) *PainPoint {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *PainPointClient) Hooks() []Hook {
	return c.hooks.PainPoint
}

// Interceptors returns the client interceptors.
func (c *PainPointClient) Interceptors() []Interceptor {
	return c.inters.PainPoint
}

func (c *PainPointClient) mutate(ctx context.Context, m *PainPointMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&PainPointCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&PainPointUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&PainPointUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&PainPointDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown PainPoint mutation op: %q", m.Op())
	}
}

// PhaseClient is a client for the Phase schema.
type PhaseClient struct {
	config
}

// NewPhaseClient returns a client for the Phase from the given config.
func NewPhaseClient(c config) *PhaseClient {
	return &PhaseClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `phase.Hooks(f(g(h())))`.
func (c *PhaseClient) Use(hooks ...Hook) {
	c.hooks.Phase = append(c.hooks.Phase, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `phase.Intercept(f(g(h())))`.
func (c *PhaseClient) Intercept(interceptors ...Interceptor) {
	c.inters.Phase = append(c.inters.Phase, interceptors...)
}

// Create returns a builder for creating a Phase entity.
func (c *PhaseClient) Create() *PhaseCreate {
	mutation := newPhaseMutation(c.config, OpCreate)
	return &PhaseCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Phase entities.
func (c *PhaseClient) CreateBulk(builders ...*PhaseCreate) *PhaseCreateBulk {
	return &PhaseCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *PhaseClient) MapCreateBulk(slice any, setFunc func(*PhaseCreate, int)) *PhaseCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &PhaseCreateBulk{err: fmt.Errorf("calling to PhaseClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*PhaseCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &PhaseCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Phase.
func (c *PhaseClient) Update() *PhaseUpdate {
	mutation := newPhaseMutation(c.config, OpUpdate)
	return &PhaseUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *PhaseClient) UpdateOne(_m *Phase) *PhaseUpdateOne {
	mutation := newPhaseMutation(c.config, OpUpdateOne, withPhase(_m))
	return &PhaseUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *PhaseClient) UpdateOneID(id string) *PhaseUpdateOne {
	mutation := newPhaseMutation(c.config, OpUpdateOne, withPhaseID(id))
	return &PhaseUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Phase.
func (c *PhaseClient) Delete() *PhaseDelete {
	mutation := newPhaseMutation(c.config, OpDelete)
	return &PhaseDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *PhaseClient) DeleteOne(_m *Phase) *PhaseDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *PhaseClient) DeleteOneID(id string) *PhaseDeleteOne {
	builder := c.Delete().Where(phase.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &PhaseDeleteOne{builder}
}

// Query returns a query builder for Phase.
func (c *PhaseClient) Query() *PhaseQuery {
	return &PhaseQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypePhase},
		inters: c.Interceptors(),
	}
}

// Get returns a Phase entity by its id.
func (c *PhaseClient) Get(ctx context.Context, id string) (*Phase, error) {
	return c.Query().Where(phase.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *PhaseClient) GetX(ctx context.Context, id string) *Phase {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryProjects queries the projects edge of a Phase.
func (c *PhaseClient) QueryProjects(_m *Phase) *ProjectQuery {
	query := (&ProjectClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(phase.Table, phase.FieldID, id),
			sqlgraph.To(project.Table, project.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, phase.ProjectsTable, phase.ProjectsPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *PhaseClient) Hooks() []Hook {
	return c.hooks.Phase
}

// Interceptors returns the client interceptors.
func (c *PhaseClient) Interceptors() []Interceptor {
	return c.inters.Phase
}

func (c *PhaseClient) mutate(ctx context.Context, m *PhaseMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&PhaseCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&PhaseUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&PhaseUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&PhaseDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Phase mutation op: %q", m.Op())
	}
}

// PricingClient is a client for the Pricing schema.
type PricingClient struct {
	config
}

// NewPricingClient returns a client for the Pricing from the given config.
func NewPricingClient(c config) *PricingClient {
	return &PricingClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `pricing.Hooks(f(g(h())))`.
func (c *PricingClient) Use(hooks ...Hook) {
	c.hooks.Pricing = append(c.hooks.Pricing, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `pricing.Intercept(f(g(h())))`.
func (c *PricingClient) Intercept(interceptors ...Interceptor) {
	c.inters.Pricing = append(c.inters.Pricing, interceptors...)
}

// Create returns a builder for creating a Pricing entity.
func (c *PricingClient) Create() *PricingCreate {
	mutation := newPricingMutation(c.config, OpCreate)
	return &PricingCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Pricing entities.
func (c *PricingClient) CreateBulk(builders ...*PricingCreate) *PricingCreateBulk {
	return &PricingCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *PricingClient) MapCreateBulk(slice any, setFunc func(*PricingCreate, int)) *PricingCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &PricingCreateBulk{err: fmt.Errorf("calling to PricingClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*PricingCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &PricingCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Pricing.
func (c *PricingClient) Update() *PricingUpdate {
	mutation := newPricingMutation(c.config, OpUpdate)
	return &PricingUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *PricingClient) UpdateOne(_m *Pricing) *PricingUpdateOne {
	mutation := newPricingMutation(c.config, OpUpdateOne, withPricing(_m))
	return &PricingUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *PricingClient) UpdateOneID(id int) *PricingUpdateOne {
	mutation := newPricingMutation(c.config, OpUpdateOne, withPricingID(id))
	return &PricingUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Pricing.
func (c *PricingClient) Delete() *PricingDelete {
	mutation := newPricingMutation(c.config, OpDelete)
	return &PricingDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *PricingClient) DeleteOne(_m *Pricing) *PricingDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *PricingClient) DeleteOneID(id int) *PricingDeleteOne {
	builder := c.Delete().Where(pricing.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &PricingDeleteOne{builder}
}

// Query returns a query builder for Pricing.
func (c *PricingClient) Query() *PricingQuery {
	return &PricingQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypePricing},
		inters: c.Interceptors(),
	}
}

// Get returns a Pricing entity by its id.
func (c *PricingClient) Get(ctx context.Context, id int) (*Pricing, error) {
	return c.Query().Where(pricing.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *PricingClient) GetX(ctx context.Context, id int) *Pricing {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryPatterns queries the patterns edge of a Pricing.
func (c *PricingClient) QueryPatterns(_m *Pricing) *PricingPatternQuery {
	query := (&PricingPatternClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(pricing.Table, pricing.FieldID, id),
			sqlgraph.To(pricingpattern.Table, pricingpattern.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, pricing.PatternsTable, pricing.PatternsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *PricingClient) Hooks() []Hook {
	return c.hooks.Pricing
}

// Interceptors returns the client interceptors.
func (c *PricingClient) Interceptors() []Interceptor {
	return c.inters.Pricing
}

func (c *PricingClient) mutate(ctx context.Context, m *PricingMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&PricingCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&PricingUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&PricingUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&PricingDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Pricing mutation op: %q", m.Op())
	}
}

// PricingPatternClient is a client for the PricingPattern schema.
type PricingPatternClient struct {
	config
}

// NewPricingPatternClient returns a client for the PricingPattern from the given config.
func NewPricingPatternClient(c config) *PricingPatternClient {
	return &PricingPatternClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `pricingpattern.Hooks(f(g(h())))`.
func (c *PricingPatternClient) Use(hooks ...Hook) {
	c.hooks.PricingPattern = append(c.hooks.PricingPattern, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `pricingpattern.Intercept(f(g(h())))`.
func (c *PricingPatternClient) Intercept(interceptors ...Interceptor) {
	c.inters.PricingPattern = append(c.inters.PricingPattern, interceptors...)
}

// Create returns a builder for creating a PricingPattern entity.
func (c *PricingPatternClient) Create() *PricingPatternCreate {
	mutation := newPricingPatternMutation(c.config, OpCreate)
	return &PricingPatternCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of PricingPattern entities.
func (c *PricingPatternClient) CreateBulk(builders ...*PricingPatternCreate) *PricingPatternCreateBulk {
	return &PricingPatternCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *PricingPatternClient) MapCreateBulk(slice any, setFunc func(*PricingPatternCreate, int)) *PricingPatternCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &PricingPatternCreateBulk{err: fmt.Errorf("calling to PricingPatternClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*PricingPatternCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &PricingPatternCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for PricingPattern.
func (c *PricingPatternClient) Update() *PricingPatternUpdate {
	mutation := newPricingPatternMutation(c.config, OpUpdate)
	return &PricingPatternUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *PricingPatternClient) UpdateOne(_m *PricingPattern) *PricingPatternUpdateOne {
	mutation := newPricingPatternMutation(c.config, OpUpdateOne, withPricingPattern(_m))
	return &PricingPatternUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *PricingPatternClient) UpdateOneID(id int) *PricingPatternUpdateOne {
	mutation := newPricingPatternMutation(c.config, OpUpdateOne, withPricingPatternID(id))
	return &PricingPatternUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for PricingPattern.
func (c *PricingPatternClient) Delete() *PricingPatternDelete {
	mutation := newPricingPatternMutation(c.config, OpDelete)
	return &PricingPatternDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *PricingPatternClient) DeleteOne(_m *PricingPattern) *PricingPatternDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *PricingPatternClient) DeleteOneID(id int) *PricingPatternDeleteOne {
	builder := c.Delete().Where(pricingpattern.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &PricingPatternDeleteOne{builder}
}

// Query returns a query builder for PricingPattern.
func (c *PricingPatternClient) Query() *PricingPatternQuery {
	return &PricingPatternQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypePricingPattern},
		inters: c.Interceptors(),
	}
}

// Get returns a PricingPattern entity by its id.
func (c *PricingPatternClient) Get(ctx context.Context, id int) (*PricingPattern, error) {
	return c.Query().Where(pricingpattern.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *PricingPatternClient) GetX(ctx context.Context, id int) *PricingPattern {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryPricing queries the pricing edge of a PricingPattern.
func (c *PricingPatternClient) QueryPricing(_m *PricingPattern) *PricingQuery {
	query := (&PricingClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(pricingpattern.Table, pricingpattern.FieldID, id),
			sqlgraph.To(pricing.Table, pricing.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, pricingpattern.PricingTable, pricingpattern.PricingColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *PricingPatternClient) Hooks() []Hook {
	return c.hooks.PricingPattern
}

// Interceptors returns the client interceptors.
func (c *PricingPatternClient) Interceptors() []Interceptor {
	return c.inters.PricingPattern
}

func (c *PricingPatternClient) mutate(ctx context.Context, m *PricingPatternMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&PricingPatternCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&PricingPatternUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&PricingPatternUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&PricingPatternDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown PricingPattern mutation op: %q", m.Op())
	}
}

// ProjectClient is a client for the Project schema.
type ProjectClient struct {
	config
}

// NewProjectClient returns a client for the Project from the given config.
func NewProjectClient(c config) *ProjectClient {
	return &ProjectClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `project.Hooks(f(g(h())))`.
func (c *ProjectClient) Use(hooks ...Hook) {
	c.hooks.Project = append(c.hooks.Project, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `project.Intercept(f(g(h())))`.
func (c *ProjectClient) Intercept(interceptors ...Interceptor) {
	c.inters.Project = append(c.inters.Project, interceptors...)
}

// Create returns a builder for creating a Project entity.
func (c *ProjectClient) Create() *ProjectCreate {
	mutation := newProjectMutation(c.config, OpCreate)
	return &ProjectCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Project entities.
func (c *ProjectClient) CreateBulk(builders ...*ProjectCreate) *ProjectCreateBulk {
	return &ProjectCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ProjectClient) MapCreateBulk(slice any, setFunc func(*ProjectCreate, int)) *ProjectCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ProjectCreateBulk{err: fmt.Errorf("calling to ProjectClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ProjectCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ProjectCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Project.
func (c *ProjectClient) Update() *ProjectUpdate {
	mutation := newProjectMutation(c.config, OpUpdate)
	return &ProjectUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ProjectClient) UpdateOne(_m *Project) *ProjectUpdateOne {
	mutation := newProjectMutation(c.config, OpUpdateOne, withProject(_m))
	return &ProjectUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ProjectClient) UpdateOneID(id string) *ProjectUpdateOne {
	mutation := newProjectMutation(c.config, OpUpdateOne, withProjectID(id))
	return &ProjectUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Project.
func (c *ProjectClient) Delete() *ProjectDelete {
	mutation := newProjectMutation(c.config, OpDelete)
	return &ProjectDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ProjectClient) DeleteOne(_m *Project) *ProjectDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ProjectClient) DeleteOneID(id string) *ProjectDeleteOne {
	builder := c.Delete().Where(project.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ProjectDeleteOne{builder}
}

// Query returns a query builder for Project.
func (c *ProjectClient) Query() *ProjectQuery {
	return &ProjectQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeProject},
		inters: c.Interceptors(),
	}
}

// Get returns a Project entity by its id.
func (c *ProjectClient) Get(ctx context.Context, id string) (*Project, error) {
	return c.Query().Where(project.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ProjectClient) GetX(ctx context.Context, id string) *Project {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryTechs queries the techs edge of a Project.
func (c *ProjectClient) QueryTechs(_m *Project) *TechQuery {
	query := (&TechClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(project.Table, project.FieldID, id),
			sqlgraph.To(tech.Table, tech.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, project.TechsTable, project.TechsPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryPhases queries the phases edge of a Project.
func (c *ProjectClient) QueryPhases(_m *Project) *PhaseQuery {
	query := (&PhaseClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(project.Table, project.FieldID, id),
			sqlgraph.To(phase.Table, phase.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, project.PhasesTable, project.PhasesPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *ProjectClient) Hooks() []Hook {
	return c.hooks.Project
}

// Interceptors returns the client interceptors.
func (c *ProjectClient) Interceptors() []Interceptor {
	return c.inters.Project
}

func (c *ProjectClient) mutate(ctx context.Context, m *ProjectMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ProjectCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ProjectUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ProjectUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ProjectDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Project mutation op: %q", m.Op())
	}
}

// RequirementClient is a client for the Requirement schema.
type RequirementClient struct {
	config
}

// NewRequirementClient returns a client for the Requirement from the given config.
func NewRequirementClient(c config) *RequirementClient {
	return &RequirementClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `requirement.Hooks(f(g(h())))`.
func (c *RequirementClient) Use(hooks ...Hook) {
	c.hooks.Requirement = append(c.hooks.Requirement, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `requirement.Intercept(f(g(h())))`.
func (c *RequirementClient) Intercept(interceptors ...Interceptor) {
	c.inters.Requirement = append(c.inters.Requirement, interceptors...)
}

// Create returns a builder for creating a Requirement entity.
func (c *RequirementClient) Create() *RequirementCreate {
	mutation := newRequirementMutation(c.config, OpCreate)
	return &RequirementCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Requirement entities.
func (c *RequirementClient) CreateBulk(builders ...*RequirementCreate) *RequirementCreateBulk {
	return &RequirementCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *RequirementClient) MapCreateBulk(slice any, setFunc func(*RequirementCreate, int)) *RequirementCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &RequirementCreateBulk{err: fmt.Errorf("calling to RequirementClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*RequirementCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &RequirementCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Requirement.
func (c *RequirementClient) Update() *RequirementUpdate {
	mutation := newRequirementMutation(c.config, OpUpdate)
	return &RequirementUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *RequirementClient) UpdateOne(_m *Requirement) *RequirementUpdateOne {
	mutation := newRequirementMutation(c.config, OpUpdateOne, withRequirement(_m))
	return &RequirementUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *RequirementClient) UpdateOneID(id int) *RequirementUpdateOne {
	mutation := newRequirementMutation(c.config, OpUpdateOne, withRequirementID(id))
	return &RequirementUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Requirement.
func (c *RequirementClient) Delete() *RequirementDelete {
	mutation := newRequirementMutation(c.config, OpDelete)
	return &RequirementDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *RequirementClient) DeleteOne(_m *Requirement) *RequirementDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *RequirementClient) DeleteOneID(id int) *RequirementDeleteOne {
	builder := c.Delete().Where(requirement.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &RequirementDeleteOne{builder}
}

// Query returns a query builder for Requirement.
func (c *RequirementClient) Query() *RequirementQuery {
	return &RequirementQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeRequirement},
		inters: c.Interceptors(),
	}
}

// Get returns a Requirement entity by its id.
func (c *RequirementClient) Get(ctx context.Context, id int) (*Requirement, error) {
	return c.Query().Where(requirement.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *RequirementClient) GetX(ctx context.Context, id int) *Requirement {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *RequirementClient) Hooks() []Hook {
	return c.hooks.Requirement
}

// Interceptors returns the client interceptors.
func (c *RequirementClient) Interceptors() []Interceptor {
	return c.inters.Requirement
}

func (c *RequirementClient) mutate(ctx context.Context, m *RequirementMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&RequirementCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&RequirementUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&RequirementUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&RequirementDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Requirement mutation op: %q", m.Op())
	}
}

// TechClient is a client for the Tech schema.
type TechClient struct {
	config
}

// NewTechClient returns a client for the Tech from the given config.
func NewTechClient(c config) *TechClient {
	return &TechClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `tech.Hooks(f(g(h())))`.
func (c *TechClient) Use(hooks ...Hook) {
	c.hooks.Tech = append(c.hooks.Tech, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `tech.Intercept(f(g(h())))`.
func (c *TechClient) Intercept(interceptors ...Interceptor) {
	c.inters.Tech = append(c.inters.Tech, interceptors...)
}

// Create returns a builder for creating a Tech entity.
func (c *TechClient) Create() *TechCreate {
	mutation := newTechMutation(c.config, OpCreate)
	return &TechCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Tech entities.
func (c *TechClient) CreateBulk(builders ...*TechCreate) *TechCreateBulk {
	return &TechCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *TechClient) MapCreateBulk(slice any, setFunc func(*TechCreate, int)) *TechCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &TechCreateBulk{err: fmt.Errorf("calling to TechClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*TechCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &TechCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Tech.
func (c *TechClient) Update() *TechUpdate {
	mutation := newTechMutation(c.config, OpUpdate)
	return &TechUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *TechClient) UpdateOne(_m *Tech) *TechUpdateOne {
	mutation := newTechMutation(c.config, OpUpdateOne, withTech(_m))
	return &TechUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *TechClient) UpdateOneID(id string) *TechUpdateOne {
	mutation := newTechMutation(c.config, OpUpdateOne, withTechID(id))
	return &TechUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Tech.
func (c *TechClient) Delete() *TechDelete {
	mutation := newTechMutation(c.config, OpDelete)
	return &TechDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *TechClient) DeleteOne(_m *Tech) *TechDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *TechClient) DeleteOneID(id string) *TechDeleteOne {
	builder := c.Delete().Where(tech.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &TechDeleteOne{builder}
}

// Query returns a query builder for Tech.
func (c *TechClient) Query() *TechQuery {
	return &TechQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeTech},
		inters: c.Interceptors(),
	}
}

// Get returns a Tech entity by its id.
func (c *TechClient) Get(ctx context.Context, id string) (*Tech, error) {
	return c.Query().Where(tech.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *TechClient) GetX(ctx context.Context, id string) *Tech {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryProjects queries the projects edge of a Tech.
func (c *TechClient) QueryProjects(_m *Tech) *ProjectQuery {
	query := (&ProjectClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(tech.Table, tech.FieldID, id),
			sqlgraph.To(project.Table, project.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, tech.ProjectsTable, tech.ProjectsPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *TechClient) Hooks() []Hook {
	return c.hooks.Tech
}

// Interceptors returns the client interceptors.
func (c *TechClient) Interceptors() []Interceptor {
	return c.inters.Tech
}

func (c *TechClient) mutate(ctx context.Context, m *TechMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&TechCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&TechUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&TechUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&TechDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Tech mutation op: %q", m.Op())
	}
}

// WorkConditionClient is a client for the WorkCondition schema.
type WorkConditionClient struct {
	config
}

// NewWorkConditionClient returns a client for the WorkCondition from the given config.
func NewWorkConditionClient(c config) *WorkConditionClient {
	return &WorkConditionClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `workcondition.Hooks(f(g(h())))`.
func (c *WorkConditionClient) Use(hooks ...Hook) {
	c.hooks.WorkCondition = append(c.hooks.WorkCondition, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `workcondition.Intercept(f(g(h())))`.
func (c *WorkConditionClient) Intercept(interceptors ...Interceptor) {
	c.inters.WorkCondition = append(c.inters.WorkCondition, interceptors...)
}

// Create returns a builder for creating a WorkCondition entity.
func (c *WorkConditionClient) Create() *WorkConditionCreate {
	mutation := newWorkConditionMutation(c.config, OpCreate)
	return &WorkConditionCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of WorkCondition entities.
func (c *WorkConditionClient) CreateBulk(builders ...*WorkConditionCreate) *WorkConditionCreateBulk {
	return &WorkConditionCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *WorkConditionClient) MapCreateBulk(slice any, setFunc func(*WorkConditionCreate, int)) *WorkConditionCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &WorkConditionCreateBulk{err: fmt.Errorf("calling to WorkConditionClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*WorkConditionCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &WorkConditionCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for WorkCondition.
func (c *WorkConditionClient) Update() *WorkConditionUpdate {
	mutation := newWorkConditionMutation(c.config, OpUpdate)
	return &WorkConditionUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *WorkConditionClient) UpdateOne(_m *WorkCondition) *WorkConditionUpdateOne {
	mutation := newWorkConditionMutation(c.config, OpUpdateOne, withWorkCondition(_m))
	return &WorkConditionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *WorkConditionClient) UpdateOneID(id int) *WorkConditionUpdateOne {
	mutation := newWorkConditionMutation(c.config, OpUpdateOne, withWorkConditionID(id))
	return &WorkConditionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for WorkCondition.
func (c *WorkConditionClient) Delete() *WorkConditionDelete {
	mutation := newWorkConditionMutation(c.config, OpDelete)
	return &WorkConditionDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *WorkConditionClient) DeleteOne(_m *WorkCondition) *WorkConditionDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *WorkConditionClient) DeleteOneID(id int) *WorkConditionDeleteOne {
	builder := c.Delete().Where(workcondition.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &WorkConditionDeleteOne{builder}
}

// Query returns a query builder for WorkCondition.
func (c *WorkConditionClient) Query() *WorkConditionQuery {
	return &WorkConditionQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeWorkCondition},
		inters: c.Interceptors(),
	}
}

// Get returns a WorkCondition entity by its id.
func (c *WorkConditionClient) Get(ctx context.Context, id int) (*WorkCondition, error) {
	return c.Query().Where(workcondition.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *WorkConditionClient) GetX(ctx context.Context, id int) *WorkCondition {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *WorkConditionClient) Hooks() []Hook {
	return c.hooks.WorkCondition
}

// Interceptors returns the client interceptors.
func (c *WorkConditionClient) Interceptors() []Interceptor {
	return c.inters.WorkCondition
}

func (c *WorkConditionClient) mutate(ctx context.Context, m *WorkConditionMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&WorkConditionCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&WorkConditionUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&WorkConditionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&WorkConditionDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown WorkCondition mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		Benefit, FAQItem, PainPoint, Phase, Pricing, PricingPattern, Project,
		Requirement, Tech, WorkCondition []ent.Hook
	}
	inters struct {
		Benefit, FAQItem, PainPoint, Phase, Pricing, PricingPattern, Project,
		Requirement, Tech, WorkCondition []ent.Interceptor
	}
)
