// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/hashiguchip/resume_2026/apps/api/ent/faqitem"
)

// FAQItem is the model entity for the FAQItem schema.
type FAQItem struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Question holds the value of the "question" field.
	Question string `json:"question,omitempty"`
	// Answer holds the value of the "answer" field.
	Answer string `json:"answer,omitempty"`
	// DisplayOrder holds the value of the "display_order" field.
	DisplayOrder int `json:"display_order,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*FAQItem) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case faqitem.FieldID, faqitem.FieldDisplayOrder:
			values[i] = new(sql.NullInt64)
		case faqitem.FieldQuestion, faqitem.FieldAnswer:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the FAQItem fields.
func (_m *FAQItem) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case faqitem.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case faqitem.FieldQuestion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field question", values[i])
			} else if value.Valid {
				_m.Question = value.String
			}
		case faqitem.FieldAnswer:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field answer", values[i])
			} else if value.Valid {
				_m.Answer = value.String
			}
		case faqitem.FieldDisplayOrder:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field display_order", values[i])
			} else if value.Valid {
				_m.DisplayOrder = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the FAQItem.
// This includes values selected through modifiers, order, etc.
func (_m *FAQItem) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this FAQItem.
// Note that you need to call FAQItem.Unwrap() before calling this method if this FAQItem
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *FAQItem) Update() *FAQItemUpdateOne {
	return NewFAQItemClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the FAQItem entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *FAQItem) Unwrap() *FAQItem {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: FAQItem is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *FAQItem) String() string {
	var builder strings.Builder
	builder.WriteString("FAQItem(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("question=")
	builder.WriteString(_m.Question)
	builder.WriteString(", ")
	builder.WriteString("answer=")
	builder.WriteString(_m.Answer)
	builder.WriteString(", ")
	builder.WriteString("display_order=")
	builder.WriteString(fmt.Sprintf("%v", _m.DisplayOrder))
	builder.WriteByte(')')
	return builder.String()
}

// FAQItems is a parsable slice of FAQItem.
type FAQItems []*FAQItem
