// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/hashiguchip/resume_2026/apps/api/ent/faqitem"
	"github.com/hashiguchip/resume_2026/apps/api/ent/predicate"
)

// FAQItemUpdate is the builder for updating FAQItem entities.
type FAQItemUpdate struct {
	config
	hooks    []Hook
	mutation *FAQItemMutation
}

// Where appends a list predicates to the FAQItemUpdate builder.
func (_u *FAQItemUpdate) Where(ps ...predicate.FAQItem) *FAQItemUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetQuestion sets the "question" field.
func (_u *FAQItemUpdate) SetQuestion(v string) *FAQItemUpdate {
	_u.mutation.SetQuestion(v)
	return _u
}

// SetNillableQuestion sets the "question" field if the given value is not nil.
func (_u *FAQItemUpdate) SetNillableQuestion(v *string) *FAQItemUpdate {
	if v != nil {
		_u.SetQuestion(*v)
	}
	return _u
}

// SetAnswer sets the "answer" field.
func (_u *FAQItemUpdate) SetAnswer(v string) *FAQItemUpdate {
	_u.mutation.SetAnswer(v)
	return _u
}

// SetNillableAnswer sets the "answer" field if the given value is not nil.
func (_u *FAQItemUpdate) SetNillableAnswer(v *string) *FAQItemUpdate {
	if v != nil {
		_u.SetAnswer(*v)
	}
	return _u
}

// SetDisplayOrder sets the "display_order" field.
func (_u *FAQItemUpdate) SetDisplayOrder(v int) *FAQItemUpdate {
	_u.mutation.ResetDisplayOrder()
	_u.mutation.SetDisplayOrder(v)
	return _u
}

// SetNillableDisplayOrder sets the "display_order" field if the given value is not nil.
func (_u *FAQItemUpdate) SetNillableDisplayOrder(v *int) *FAQItemUpdate {
	if v != nil {
		_u.SetDisplayOrder(*v)
	}
	return _u
}

// AddDisplayOrder adds value to the "display_order" field.
func (_u *FAQItemUpdate) AddDisplayOrder(v int) *FAQItemUpdate {
	_u.mutation.AddDisplayOrder(v)
	return _u
}

// Mutation returns the FAQItemMutation object of the builder.
func (_u *FAQItemUpdate) Mutation() *FAQItemMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *FAQItemUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FAQItemUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *FAQItemUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FAQItemUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *FAQItemUpdate) check() error {
	if v, ok := _u.mutation.Question(); ok {
		if err := faqitem.QuestionValidator(v); err != nil {
			return &ValidationError{Name: "question", err: fmt.Errorf(`ent: validator failed for field "FAQItem.question": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Answer(); ok {
		if err := faqitem.AnswerValidator(v); err != nil {
			return &ValidationError{Name: "answer", err: fmt.Errorf(`ent: validator failed for field "FAQItem.answer": %w`, err)}
		}
	}
	return nil
}

func (_u *FAQItemUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(faqitem.Table, faqitem.Columns, sqlgraph.NewFieldSpec(faqitem.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Question(); ok {
		_spec.SetField(faqitem.FieldQuestion, field.TypeString, value)
	}
	if value, ok := _u.mutation.Answer(); ok {
		_spec.SetField(faqitem.FieldAnswer, field.TypeString, value)
	}
	if value, ok := _u.mutation.DisplayOrder(); ok {
		_spec.SetField(faqitem.FieldDisplayOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDisplayOrder(); ok {
		_spec.AddField(faqitem.FieldDisplayOrder, field.TypeInt, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{faqitem.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// FAQItemUpdateOne is the builder for updating a single FAQItem entity.
type FAQItemUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *FAQItemMutation
}

// SetQuestion sets the "question" field.
func (_u *FAQItemUpdateOne) SetQuestion(v string) *FAQItemUpdateOne {
	_u.mutation.SetQuestion(v)
	return _u
}

// SetNillableQuestion sets the "question" field if the given value is not nil.
func (_u *FAQItemUpdateOne) SetNillableQuestion(v *string) *FAQItemUpdateOne {
	if v != nil {
		_u.SetQuestion(*v)
	}
	return _u
}

// SetAnswer sets the "answer" field.
func (_u *FAQItemUpdateOne) SetAnswer(v string) *FAQItemUpdateOne {
	_u.mutation.SetAnswer(v)
	return _u
}

// SetNillableAnswer sets the "answer" field if the given value is not nil.
func (_u *FAQItemUpdateOne) SetNillableAnswer(v *string) *FAQItemUpdateOne {
	if v != nil {
		_u.SetAnswer(*v)
	}
	return _u
}

// SetDisplayOrder sets the "display_order" field.
func (_u *FAQItemUpdateOne) SetDisplayOrder(v int) *FAQItemUpdateOne {
	_u.mutation.ResetDisplayOrder()
	_u.mutation.SetDisplayOrder(v)
	return _u
}

// SetNillableDisplayOrder sets the "display_order" field if the given value is not nil.
func (_u *FAQItemUpdateOne) SetNillableDisplayOrder(v *int) *FAQItemUpdateOne {
	if v != nil {
		_u.SetDisplayOrder(*v)
	}
	return _u
}

// AddDisplayOrder adds value to the "display_order" field.
func (_u *FAQItemUpdateOne) AddDisplayOrder(v int) *FAQItemUpdateOne {
	_u.mutation.AddDisplayOrder(v)
	return _u
}

// Mutation returns the FAQItemMutation object of the builder.
func (_u *FAQItemUpdateOne) Mutation() *FAQItemMutation {
	return _u.mutation
}

// Where appends a list predicates to the FAQItemUpdate builder.
func (_u *FAQItemUpdateOne) Where(ps ...predicate.FAQItem) *FAQItemUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *FAQItemUpdateOne) Select(field string, fields ...string) *FAQItemUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated FAQItem entity.
func (_u *FAQItemUpdateOne) Save(ctx context.Context) (*FAQItem, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FAQItemUpdateOne) SaveX(ctx context.Context) *FAQItem {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *FAQItemUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FAQItemUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *FAQItemUpdateOne) check() error {
	if v, ok := _u.mutation.Question(); ok {
		if err := faqitem.QuestionValidator(v); err != nil {
			return &ValidationError{Name: "question", err: fmt.Errorf(`ent: validator failed for field "FAQItem.question": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Answer(); ok {
		if err := faqitem.AnswerValidator(v); err != nil {
			return &ValidationError{Name: "answer", err: fmt.Errorf(`ent: validator failed for field "FAQItem.answer": %w`, err)}
		}
	}
	return nil
}

func (_u *FAQItemUpdateOne) sqlSave(ctx context.Context) (_node *FAQItem, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(faqitem.Table, faqitem.Columns, sqlgraph.NewFieldSpec(faqitem.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "FAQItem.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, faqitem.FieldID)
		for _, f := range fields {
			if !faqitem.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != faqitem.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Question(); ok {
		_spec.SetField(faqitem.FieldQuestion, field.TypeString, value)
	}
	if value, ok := _u.mutation.Answer(); ok {
		_spec.SetField(faqitem.FieldAnswer, field.TypeString, value)
	}
	if value, ok := _u.mutation.DisplayOrder(); ok {
		_spec.SetField(faqitem.FieldDisplayOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDisplayOrder(); ok {
		_spec.AddField(faqitem.FieldDisplayOrder, field.TypeInt, value)
	}
	_node = &FAQItem{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{faqitem.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
