// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/hashiguchip/resume_2026/apps/api/ent/painpoint"
	"github.com/hashiguchip/resume_2026/apps/api/ent/predicate"
)

// PainPointUpdate is the builder for updating PainPoint entities.
type PainPointUpdate struct {
	config
	hooks    []Hook
	mutation *PainPointMutation
}

// Where appends a list predicates to the PainPointUpdate builder.
func (_u *PainPointUpdate) Where(ps ...predicate.PainPoint) *PainPointUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTitle sets the "title" field.
func (_u *PainPointUpdate) SetTitle(v string) *PainPointUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *PainPointUpdate) SetNillableTitle(v *string) *PainPointUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *PainPointUpdate) SetDescription(v string) *PainPointUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *PainPointUpdate) SetNillableDescription(v *string) *PainPointUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetDisplayOrder sets the "display_order" field.
func (_u *PainPointUpdate) SetDisplayOrder(v int) *PainPointUpdate {
	_u.mutation.ResetDisplayOrder()
	_u.mutation.SetDisplayOrder(v)
	return _u
}

// SetNillableDisplayOrder sets the "display_order" field if the given value is not nil.
func (_u *PainPointUpdate) SetNillableDisplayOrder(v *int) *PainPointUpdate {
	if v != nil {
		_u.SetDisplayOrder(*v)
	}
	return _u
}

// AddDisplayOrder adds value to the "display_order" field.
func (_u *PainPointUpdate) AddDisplayOrder(v int) *PainPointUpdate {
	_u.mutation.AddDisplayOrder(v)
	return _u
}

// Mutation returns the PainPointMutation object of the builder.
func (_u *PainPointUpdate) Mutation() *PainPointMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PainPointUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PainPointUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PainPointUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PainPointUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PainPointUpdate) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := painpoint.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "PainPoint.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := painpoint.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "PainPoint.description": %w`, err)}
		}
	}
	return nil
}

func (_u *PainPointUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(painpoint.Table, painpoint.Columns, sqlgraph.NewFieldSpec(painpoint.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(painpoint.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(painpoint.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.DisplayOrder(); ok {
		_spec.SetField(painpoint.FieldDisplayOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDisplayOrder(); ok {
		_spec.AddField(painpoint.FieldDisplayOrder, field.TypeInt, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{painpoint.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PainPointUpdateOne is the builder for updating a single PainPoint entity.
type PainPointUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PainPointMutation
}

// SetTitle sets the "title" field.
func (_u *PainPointUpdateOne) SetTitle(v string) *PainPointUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *PainPointUpdateOne) SetNillableTitle(v *string) *PainPointUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *PainPointUpdateOne) SetDescription(v string) *PainPointUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *PainPointUpdateOne) SetNillableDescription(v *string) *PainPointUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetDisplayOrder sets the "display_order" field.
func (_u *PainPointUpdateOne) SetDisplayOrder(v int) *PainPointUpdateOne {
	_u.mutation.ResetDisplayOrder()
	_u.mutation.SetDisplayOrder(v)
	return _u
}

// SetNillableDisplayOrder sets the "display_order" field if the given value is not nil.
func (_u *PainPointUpdateOne) SetNillableDisplayOrder(v *int) *PainPointUpdateOne {
	if v != nil {
		_u.SetDisplayOrder(*v)
	}
	return _u
}

// AddDisplayOrder adds value to the "display_order" field.
func (_u *PainPointUpdateOne) AddDisplayOrder(v int) *PainPointUpdateOne {
	_u.mutation.AddDisplayOrder(v)
	return _u
}

// Mutation returns the PainPointMutation object of the builder.
func (_u *PainPointUpdateOne) Mutation() *PainPointMutation {
	return _u.mutation
}

// Where appends a list predicates to the PainPointUpdate builder.
func (_u *PainPointUpdateOne) Where(ps ...predicate.PainPoint) *PainPointUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PainPointUpdateOne) Select(field string, fields ...string) *PainPointUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PainPoint entity.
func (_u *PainPointUpdateOne) Save(ctx context.Context) (*PainPoint, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PainPointUpdateOne) SaveX(ctx context.Context) *PainPoint {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PainPointUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PainPointUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PainPointUpdateOne) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := painpoint.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "PainPoint.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := painpoint.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "PainPoint.description": %w`, err)}
		}
	}
	return nil
}

func (_u *PainPointUpdateOne) sqlSave(ctx context.Context) (_node *PainPoint, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(painpoint.Table, painpoint.Columns, sqlgraph.NewFieldSpec(painpoint.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PainPoint.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, painpoint.FieldID)
		for _, f := range fields {
			if !painpoint.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != painpoint.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(painpoint.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(painpoint.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.DisplayOrder(); ok {
		_spec.SetField(painpoint.FieldDisplayOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDisplayOrder(); ok {
		_spec.AddField(painpoint.FieldDisplayOrder, field.TypeInt, value)
	}
	_node = &PainPoint{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{painpoint.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
