// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/hashiguchip/resume_2026/apps/api/ent/painpoint"
)

// PainPointCreate is the builder for creating a PainPoint entity.
type PainPointCreate struct {
	config
	mutation *PainPointMutation
	hooks    []Hook
}

// SetTitle sets the "title" field.
func (_c *PainPointCreate) SetTitle(v string) *PainPointCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *PainPointCreate) SetDescription(v string) *PainPointCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetDisplayOrder sets the "display_order" field.
func (_c *PainPointCreate) SetDisplayOrder(v int) *PainPointCreate {
	_c.mutation.SetDisplayOrder(v)
	return _c
}

// SetNillableDisplayOrder sets the "display_order" field if the given value is not nil.
func (_c *PainPointCreate) SetNillableDisplayOrder(v *int) *PainPointCreate {
	if v != nil {
		_c.SetDisplayOrder(*v)
	}
	return _c
}

// Mutation returns the PainPointMutation object of the builder.
func (_c *PainPointCreate) Mutation() *PainPointMutation {
	return _c.mutation
}

// Save creates the PainPoint in the database.
func (_c *PainPointCreate) Save(ctx context.Context) (*PainPoint, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PainPointCreate) SaveX(ctx context.Context) *PainPoint {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PainPointCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PainPointCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PainPointCreate) defaults() {
	if _, ok := _c.mutation.DisplayOrder(); !ok {
		v := painpoint.DefaultDisplayOrder
		_c.mutation.SetDisplayOrder(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PainPointCreate) check() error {
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "PainPoint.title"`)}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := painpoint.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "PainPoint.title": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "PainPoint.description"`)}
	}
	if v, ok := _c.mutation.Description(); ok {
		if err := painpoint.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "PainPoint.description": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DisplayOrder(); !ok {
		return &ValidationError{Name: "display_order", err: errors.New(`ent: missing required field "PainPoint.display_order"`)}
	}
	return nil
}

func (_c *PainPointCreate) sqlSave(ctx context.Context) (*PainPoint, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PainPointCreate) createSpec() (*PainPoint, *sqlgraph.CreateSpec) {
	var (
		_node = &PainPoint{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(painpoint.Table, sqlgraph.NewFieldSpec(painpoint.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(painpoint.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(painpoint.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.DisplayOrder(); ok {
		_spec.SetField(painpoint.FieldDisplayOrder, field.TypeInt, value)
		_node.DisplayOrder = value
	}
	return _node, _spec
}

// PainPointCreateBulk is the builder for creating many PainPoint entities in bulk.
type PainPointCreateBulk struct {
	config
	err      error
	builders []*PainPointCreate
}

// Save creates the PainPoint entities in the database.
func (_c *PainPointCreateBulk) Save(ctx context.Context) ([]*PainPoint, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PainPoint, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PainPointMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PainPointCreateBulk) SaveX(ctx context.Context) []*PainPoint {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PainPointCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PainPointCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
