// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/hashiguchip/resume_2026/apps/api/ent/requirement"
)

// RequirementCreate is the builder for creating a Requirement entity.
type RequirementCreate struct {
	config
	mutation *RequirementMutation
	hooks    []Hook
}

// SetKind sets the "kind" field.
func (_c *RequirementCreate) SetKind(v requirement.Kind) *RequirementCreate {
	_c.mutation.SetKind(v)
	return _c
}

// SetText sets the "text" field.
func (_c *RequirementCreate) SetText(v string) *RequirementCreate {
	_c.mutation.SetText(v)
	return _c
}

// SetDisplayOrder sets the "display_order" field.
func (_c *RequirementCreate) SetDisplayOrder(v int) *RequirementCreate {
	_c.mutation.SetDisplayOrder(v)
	return _c
}

// SetNillableDisplayOrder sets the "display_order" field if the given value is not nil.
func (_c *RequirementCreate) SetNillableDisplayOrder(v *int) *RequirementCreate {
	if v != nil {
		_c.SetDisplayOrder(*v)
	}
	return _c
}

// Mutation returns the RequirementMutation object of the builder.
func (_c *RequirementCreate) Mutation() *RequirementMutation {
	return _c.mutation
}

// Save creates the Requirement in the database.
func (_c *RequirementCreate) Save(ctx context.Context) (*Requirement, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RequirementCreate) SaveX(ctx context.Context) *Requirement {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RequirementCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RequirementCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RequirementCreate) defaults() {
	if _, ok := _c.mutation.DisplayOrder(); !ok {
		v := requirement.DefaultDisplayOrder
		_c.mutation.SetDisplayOrder(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RequirementCreate) check() error {
	if _, ok := _c.mutation.Kind(); !ok {
		return &ValidationError{Name: "kind", err: errors.New(`ent: missing required field "Requirement.kind"`)}
	}
	if v, ok := _c.mutation.Kind(); ok {
		if err := requirement.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "Requirement.kind": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Text(); !ok {
		return &ValidationError{Name: "text", err: errors.New(`ent: missing required field "Requirement.text"`)}
	}
	if v, ok := _c.mutation.Text(); ok {
		if err := requirement.TextValidator(v); err != nil {
			return &ValidationError{Name: "text", err: fmt.Errorf(`ent: validator failed for field "Requirement.text": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DisplayOrder(); !ok {
		return &ValidationError{Name: "display_order", err: errors.New(`ent: missing required field "Requirement.display_order"`)}
	}
	return nil
}

func (_c *RequirementCreate) sqlSave(ctx context.Context) (*Requirement, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RequirementCreate) createSpec() (*Requirement, *sqlgraph.CreateSpec) {
	var (
		_node = &Requirement{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(requirement.Table, sqlgraph.NewFieldSpec(requirement.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Kind(); ok {
		_spec.SetField(requirement.FieldKind, field.TypeEnum, value)
		_node.Kind = value
	}
	if value, ok := _c.mutation.Text(); ok {
		_spec.SetField(requirement.FieldText, field.TypeString, value)
		_node.Text = value
	}
	if value, ok := _c.mutation.DisplayOrder(); ok {
		_spec.SetField(requirement.FieldDisplayOrder, field.TypeInt, value)
		_node.DisplayOrder = value
	}
	return _node, _spec
}

// RequirementCreateBulk is the builder for creating many Requirement entities in bulk.
type RequirementCreateBulk struct {
	config
	err      error
	builders []*RequirementCreate
}

// Save creates the Requirement entities in the database.
func (_c *RequirementCreateBulk) Save(ctx context.Context) ([]*Requirement, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Requirement, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RequirementMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RequirementCreateBulk) SaveX(ctx context.Context) []*Requirement {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RequirementCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RequirementCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
