// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/hashiguchip/resume_2026/apps/api/ent/predicate"
	"github.com/hashiguchip/resume_2026/apps/api/ent/requirement"
)

// RequirementUpdate is the builder for updating Requirement entities.
type RequirementUpdate struct {
	config
	hooks    []Hook
	mutation *RequirementMutation
}

// Where appends a list predicates to the RequirementUpdate builder.
func (_u *RequirementUpdate) Where(ps ...predicate.Requirement) *RequirementUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetKind sets the "kind" field.
func (_u *RequirementUpdate) SetKind(v requirement.Kind) *RequirementUpdate {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *RequirementUpdate) SetNillableKind(v *requirement.Kind) *RequirementUpdate {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetText sets the "text" field.
func (_u *RequirementUpdate) SetText(v string) *RequirementUpdate {
	_u.mutation.SetText(v)
	return _u
}

// SetNillableText sets the "text" field if the given value is not nil.
func (_u *RequirementUpdate) SetNillableText(v *string) *RequirementUpdate {
	if v != nil {
		_u.SetText(*v)
	}
	return _u
}

// SetDisplayOrder sets the "display_order" field.
func (_u *RequirementUpdate) SetDisplayOrder(v int) *RequirementUpdate {
	_u.mutation.ResetDisplayOrder()
	_u.mutation.SetDisplayOrder(v)
	return _u
}

// SetNillableDisplayOrder sets the "display_order" field if the given value is not nil.
func (_u *RequirementUpdate) SetNillableDisplayOrder(v *int) *RequirementUpdate {
	if v != nil {
		_u.SetDisplayOrder(*v)
	}
	return _u
}

// AddDisplayOrder adds value to the "display_order" field.
func (_u *RequirementUpdate) AddDisplayOrder(v int) *RequirementUpdate {
	_u.mutation.AddDisplayOrder(v)
	return _u
}

// Mutation returns the RequirementMutation object of the builder.
func (_u *RequirementUpdate) Mutation() *RequirementMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RequirementUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RequirementUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RequirementUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RequirementUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RequirementUpdate) check() error {
	if v, ok := _u.mutation.Kind(); ok {
		if err := requirement.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "Requirement.kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Text(); ok {
		if err := requirement.TextValidator(v); err != nil {
			return &ValidationError{Name: "text", err: fmt.Errorf(`ent: validator failed for field "Requirement.text": %w`, err)}
		}
	}
	return nil
}

func (_u *RequirementUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(requirement.Table, requirement.Columns, sqlgraph.NewFieldSpec(requirement.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(requirement.FieldKind, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Text(); ok {
		_spec.SetField(requirement.FieldText, field.TypeString, value)
	}
	if value, ok := _u.mutation.DisplayOrder(); ok {
		_spec.SetField(requirement.FieldDisplayOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDisplayOrder(); ok {
		_spec.AddField(requirement.FieldDisplayOrder, field.TypeInt, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{requirement.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RequirementUpdateOne is the builder for updating a single Requirement entity.
type RequirementUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RequirementMutation
}

// SetKind sets the "kind" field.
func (_u *RequirementUpdateOne) SetKind(v requirement.Kind) *RequirementUpdateOne {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *RequirementUpdateOne) SetNillableKind(v *requirement.Kind) *RequirementUpdateOne {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetText sets the "text" field.
func (_u *RequirementUpdateOne) SetText(v string) *RequirementUpdateOne {
	_u.mutation.SetText(v)
	return _u
}

// SetNillableText sets the "text" field if the given value is not nil.
func (_u *RequirementUpdateOne) SetNillableText(v *string) *RequirementUpdateOne {
	if v != nil {
		_u.SetText(*v)
	}
	return _u
}

// SetDisplayOrder sets the "display_order" field.
func (_u *RequirementUpdateOne) SetDisplayOrder(v int) *RequirementUpdateOne {
	_u.mutation.ResetDisplayOrder()
	_u.mutation.SetDisplayOrder(v)
	return _u
}

// SetNillableDisplayOrder sets the "display_order" field if the given value is not nil.
func (_u *RequirementUpdateOne) SetNillableDisplayOrder(v *int) *RequirementUpdateOne {
	if v != nil {
		_u.SetDisplayOrder(*v)
	}
	return _u
}

// AddDisplayOrder adds value to the "display_order" field.
func (_u *RequirementUpdateOne) AddDisplayOrder(v int) *RequirementUpdateOne {
	_u.mutation.AddDisplayOrder(v)
	return _u
}

// Mutation returns the RequirementMutation object of the builder.
func (_u *RequirementUpdateOne) Mutation() *RequirementMutation {
	return _u.mutation
}

// Where appends a list predicates to the RequirementUpdate builder.
func (_u *RequirementUpdateOne) Where(ps ...predicate.Requirement) *RequirementUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RequirementUpdateOne) Select(field string, fields ...string) *RequirementUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Requirement entity.
func (_u *RequirementUpdateOne) Save(ctx context.Context) (*Requirement, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RequirementUpdateOne) SaveX(ctx context.Context) *Requirement {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RequirementUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RequirementUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RequirementUpdateOne) check() error {
	if v, ok := _u.mutation.Kind(); ok {
		if err := requirement.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "Requirement.kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Text(); ok {
		if err := requirement.TextValidator(v); err != nil {
			return &ValidationError{Name: "text", err: fmt.Errorf(`ent: validator failed for field "Requirement.text": %w`, err)}
		}
	}
	return nil
}

func (_u *RequirementUpdateOne) sqlSave(ctx context.Context) (_node *Requirement, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(requirement.Table, requirement.Columns, sqlgraph.NewFieldSpec(requirement.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Requirement.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, requirement.FieldID)
		for _, f := range fields {
			if !requirement.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != requirement.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(requirement.FieldKind, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Text(); ok {
		_spec.SetField(requirement.FieldText, field.TypeString, value)
	}
	if value, ok := _u.mutation.DisplayOrder(); ok {
		_spec.SetField(requirement.FieldDisplayOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDisplayOrder(); ok {
		_spec.AddField(requirement.FieldDisplayOrder, field.TypeInt, value)
	}
	_node = &Requirement{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{requirement.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
