// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/hashiguchip/resume_2026/apps/api/ent/project"
	"github.com/hashiguchip/resume_2026/apps/api/ent/tech"
)

// TechCreate is the builder for creating a Tech entity.
type TechCreate struct {
	config
	mutation *TechMutation
	hooks    []Hook
}

// SetLabel sets the "label" field.
func (_c *TechCreate) SetLabel(v string) *TechCreate {
	_c.mutation.SetLabel(v)
	return _c
}

// SetCategory sets the "category" field.
func (_c *TechCreate) SetCategory(v string) *TechCreate {
	_c.mutation.SetCategory(v)
	return _c
}

// SetDisplayOrder sets the "display_order" field.
func (_c *TechCreate) SetDisplayOrder(v int) *TechCreate {
	_c.mutation.SetDisplayOrder(v)
	return _c
}

// SetNillableDisplayOrder sets the "display_order" field if the given value is not nil.
func (_c *TechCreate) SetNillableDisplayOrder(v *int) *TechCreate {
	if v != nil {
		_c.SetDisplayOrder(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *TechCreate) SetID(v string) *TechCreate {
	_c.mutation.SetID(v)
	return _c
}

// AddProjectIDs adds the "projects" edge to the Project entity by IDs.
func (_c *TechCreate) AddProjectIDs(ids ...string) *TechCreate {
	_c.mutation.AddProjectIDs(ids...)
	return _c
}

// AddProjects adds the "projects" edges to the Project entity.
func (_c *TechCreate) AddProjects(v ...*Project) *TechCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddProjectIDs(ids...)
}

// Mutation returns the TechMutation object of the builder.
func (_c *TechCreate) Mutation() *TechMutation {
	return _c.mutation
}

// Save creates the Tech in the database.
func (_c *TechCreate) Save(ctx context.Context) (*Tech, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TechCreate) SaveX(ctx context.Context) *Tech {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TechCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TechCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TechCreate) defaults() {
	if _, ok := _c.mutation.DisplayOrder(); !ok {
		v := tech.DefaultDisplayOrder
		_c.mutation.SetDisplayOrder(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TechCreate) check() error {
	if _, ok := _c.mutation.Label(); !ok {
		return &ValidationError{Name: "label", err: errors.New(`ent: missing required field "Tech.label"`)}
	}
	if v, ok := _c.mutation.Label(); ok {
		if err := tech.LabelValidator(v); err != nil {
			return &ValidationError{Name: "label", err: fmt.Errorf(`ent: validator failed for field "Tech.label": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Category(); !ok {
		return &ValidationError{Name: "category", err: errors.New(`ent: missing required field "Tech.category"`)}
	}
	if v, ok := _c.mutation.Category(); ok {
		if err := tech.CategoryValidator(v); err != nil {
			return &ValidationError{Name: "category", err: fmt.Errorf(`ent: validator failed for field "Tech.category": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DisplayOrder(); !ok {
		return &ValidationError{Name: "display_order", err: errors.New(`ent: missing required field "Tech.display_order"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := tech.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "Tech.id": %w`, err)}
		}
	}
	return nil
}

func (_c *TechCreate) sqlSave(ctx context.Context) (*Tech, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Tech.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TechCreate) createSpec() (*Tech, *sqlgraph.CreateSpec) {
	var (
		_node = &Tech{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(tech.Table, sqlgraph.NewFieldSpec(tech.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Label(); ok {
		_spec.SetField(tech.FieldLabel, field.TypeString, value)
		_node.Label = value
	}
	if value, ok := _c.mutation.Category(); ok {
		_spec.SetField(tech.FieldCategory, field.TypeString, value)
		_node.Category = value
	}
	if value, ok := _c.mutation.DisplayOrder(); ok {
		_spec.SetField(tech.FieldDisplayOrder, field.TypeInt, value)
		_node.DisplayOrder = value
	}
	if nodes := _c.mutation.ProjectsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   tech.ProjectsTable,
			Columns: tech.ProjectsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// TechCreateBulk is the builder for creating many Tech entities in bulk.
type TechCreateBulk struct {
	config
	err      error
	builders []*TechCreate
}

// Save creates the Tech entities in the database.
func (_c *TechCreateBulk) Save(ctx context.Context) ([]*Tech, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Tech, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TechMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TechCreateBulk) SaveX(ctx context.Context) []*Tech {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TechCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TechCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
