// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/hashiguchip/resume_2026/apps/api/ent/tech"
)

// Tech is the model entity for the Tech schema.
type Tech struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// Label holds the value of the "label" field.
	Label string `json:"label,omitempty"`
	// Category holds the value of the "category" field.
	Category string `json:"category,omitempty"`
	// DisplayOrder holds the value of the "display_order" field.
	DisplayOrder int `json:"display_order,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TechQuery when eager-loading is set.
	Edges        TechEdges `json:"edges"`
	selectValues sql.SelectValues
}

// TechEdges holds the relations/edges for other nodes in the graph.
type TechEdges struct {
	// Projects holds the value of the projects edge.
	Projects []*Project `json:"projects,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ProjectsOrErr returns the Projects value or an error if the edge
// was not loaded in eager-loading.
func (e TechEdges) ProjectsOrErr() ([]*Project, error) {
	if e.loadedTypes[0] {
		return e.Projects, nil
	}
	return nil, &NotLoadedError{edge: "projects"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Tech) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case tech.FieldDisplayOrder:
			values[i] = new(sql.NullInt64)
		case tech.FieldID, tech.FieldLabel, tech.FieldCategory:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Tech fields.
func (_m *Tech) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case tech.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case tech.FieldLabel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field label", values[i])
			} else if value.Valid {
				_m.Label = value.String
			}
		case tech.FieldCategory:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field category", values[i])
			} else if value.Valid {
				_m.Category = value.String
			}
		case tech.FieldDisplayOrder:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field display_order", values[i])
			} else if value.Valid {
				_m.DisplayOrder = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Tech.
// This includes values selected through modifiers, order, etc.
func (_m *Tech) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryProjects queries the "projects" edge of the Tech entity.
func (_m *Tech) QueryProjects() *ProjectQuery {
	return NewTechClient(_m.config).QueryProjects(_m)
}

// Update returns a builder for updating this Tech.
// Note that you need to call Tech.Unwrap() before calling this method if this Tech
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Tech) Update() *TechUpdateOne {
	return NewTechClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Tech entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Tech) Unwrap() *Tech {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Tech is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Tech) String() string {
	var builder strings.Builder
	builder.WriteString("Tech(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("label=")
	builder.WriteString(_m.Label)
	builder.WriteString(", ")
	builder.WriteString("category=")
	builder.WriteString(_m.Category)
	builder.WriteString(", ")
	builder.WriteString("display_order=")
	builder.WriteString(fmt.Sprintf("%v", _m.DisplayOrder))
	builder.WriteByte(')')
	return builder.String()
}

// Teches is a parsable slice of Tech.
type Teches []*Tech
