// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/hashiguchip/resume_2026/apps/api/ent/workcondition"
)

// WorkConditionCreate is the builder for creating a WorkCondition entity.
type WorkConditionCreate struct {
	config
	mutation *WorkConditionMutation
	hooks    []Hook
}

// SetLabel sets the "label" field.
func (_c *WorkConditionCreate) SetLabel(v string) *WorkConditionCreate {
	_c.mutation.SetLabel(v)
	return _c
}

// SetValue sets the "value" field.
func (_c *WorkConditionCreate) SetValue(v string) *WorkConditionCreate {
	_c.mutation.SetValue(v)
	return _c
}

// SetDisplayOrder sets the "display_order" field.
func (_c *WorkConditionCreate) SetDisplayOrder(v int) *WorkConditionCreate {
	_c.mutation.SetDisplayOrder(v)
	return _c
}

// SetNillableDisplayOrder sets the "display_order" field if the given value is not nil.
func (_c *WorkConditionCreate) SetNillableDisplayOrder(v *int) *WorkConditionCreate {
	if v != nil {
		_c.SetDisplayOrder(*v)
	}
	return _c
}

// Mutation returns the WorkConditionMutation object of the builder.
func (_c *WorkConditionCreate) Mutation() *WorkConditionMutation {
	return _c.mutation
}

// Save creates the WorkCondition in the database.
func (_c *WorkConditionCreate) Save(ctx context.Context) (*WorkCondition, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *WorkConditionCreate) SaveX(ctx context.Context) *WorkCondition {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WorkConditionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WorkConditionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *WorkConditionCreate) defaults() {
	if _, ok := _c.mutation.DisplayOrder(); !ok {
		v := workcondition.DefaultDisplayOrder
		_c.mutation.SetDisplayOrder(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *WorkConditionCreate) check() error {
	if _, ok := _c.mutation.Label(); !ok {
		return &ValidationError{Name: "label", err: errors.New(`ent: missing required field "WorkCondition.label"`)}
	}
	if v, ok := _c.mutation.Label(); ok {
		if err := workcondition.LabelValidator(v); err != nil {
			return &ValidationError{Name: "label", err: fmt.Errorf(`ent: validator failed for field "WorkCondition.label": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Value(); !ok {
		return &ValidationError{Name: "value", err: errors.New(`ent: missing required field "WorkCondition.value"`)}
	}
	if v, ok := _c.mutation.Value(); ok {
		if err := workcondition.ValueValidator(v); err != nil {
			return &ValidationError{Name: "value", err: fmt.Errorf(`ent: validator failed for field "WorkCondition.value": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DisplayOrder(); !ok {
		return &ValidationError{Name: "display_order", err: errors.New(`ent: missing required field "WorkCondition.display_order"`)}
	}
	return nil
}

func (_c *WorkConditionCreate) sqlSave(ctx context.Context) (*WorkCondition, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *WorkConditionCreate) createSpec() (*WorkCondition, *sqlgraph.CreateSpec) {
	var (
		_node = &WorkCondition{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(workcondition.Table, sqlgraph.NewFieldSpec(workcondition.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Label(); ok {
		_spec.SetField(workcondition.FieldLabel, field.TypeString, value)
		_node.Label = value
	}
	if value, ok := _c.mutation.Value(); ok {
		_spec.SetField(workcondition.FieldValue, field.TypeString, value)
		_node.Value = value
	}
	if value, ok := _c.mutation.DisplayOrder(); ok {
		_spec.SetField(workcondition.FieldDisplayOrder, field.TypeInt, value)
		_node.DisplayOrder = value
	}
	return _node, _spec
}

// WorkConditionCreateBulk is the builder for creating many WorkCondition entities in bulk.
type WorkConditionCreateBulk struct {
	config
	err      error
	builders []*WorkConditionCreate
}

// Save creates the WorkCondition entities in the database.
func (_c *WorkConditionCreateBulk) Save(ctx context.Context) ([]*WorkCondition, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*WorkCondition, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*WorkConditionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *WorkConditionCreateBulk) SaveX(ctx context.Context) []*WorkCondition {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WorkConditionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WorkConditionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
