// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/hashiguchip/resume_2026/apps/api/ent/predicate"
	"github.com/hashiguchip/resume_2026/apps/api/ent/workcondition"
)

// WorkConditionUpdate is the builder for updating WorkCondition entities.
type WorkConditionUpdate struct {
	config
	hooks    []Hook
	mutation *WorkConditionMutation
}

// Where appends a list predicates to the WorkConditionUpdate builder.
func (_u *WorkConditionUpdate) Where(ps ...predicate.WorkCondition) *WorkConditionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetLabel sets the "label" field.
func (_u *WorkConditionUpdate) SetLabel(v string) *WorkConditionUpdate {
	_u.mutation.SetLabel(v)
	return _u
}

// SetNillableLabel sets the "label" field if the given value is not nil.
func (_u *WorkConditionUpdate) SetNillableLabel(v *string) *WorkConditionUpdate {
	if v != nil {
		_u.SetLabel(*v)
	}
	return _u
}

// SetValue sets the "value" field.
func (_u *WorkConditionUpdate) SetValue(v string) *WorkConditionUpdate {
	_u.mutation.SetValue(v)
	return _u
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (_u *WorkConditionUpdate) SetNillableValue(v *string) *WorkConditionUpdate {
	if v != nil {
		_u.SetValue(*v)
	}
	return _u
}

// SetDisplayOrder sets the "display_order" field.
func (_u *WorkConditionUpdate) SetDisplayOrder(v int) *WorkConditionUpdate {
	_u.mutation.ResetDisplayOrder()
	_u.mutation.SetDisplayOrder(v)
	return _u
}

// SetNillableDisplayOrder sets the "display_order" field if the given value is not nil.
func (_u *WorkConditionUpdate) SetNillableDisplayOrder(v *int) *WorkConditionUpdate {
	if v != nil {
		_u.SetDisplayOrder(*v)
	}
	return _u
}

// AddDisplayOrder adds value to the "display_order" field.
func (_u *WorkConditionUpdate) AddDisplayOrder(v int) *WorkConditionUpdate {
	_u.mutation.AddDisplayOrder(v)
	return _u
}

// Mutation returns the WorkConditionMutation object of the builder.
func (_u *WorkConditionUpdate) Mutation() *WorkConditionMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *WorkConditionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WorkConditionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *WorkConditionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WorkConditionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *WorkConditionUpdate) check() error {
	if v, ok := _u.mutation.Label(); ok {
		if err := workcondition.LabelValidator(v); err != nil {
			return &ValidationError{Name: "label", err: fmt.Errorf(`ent: validator failed for field "WorkCondition.label": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Value(); ok {
		if err := workcondition.ValueValidator(v); err != nil {
			return &ValidationError{Name: "value", err: fmt.Errorf(`ent: validator failed for field "WorkCondition.value": %w`, err)}
		}
	}
	return nil
}

func (_u *WorkConditionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(workcondition.Table, workcondition.Columns, sqlgraph.NewFieldSpec(workcondition.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Label(); ok {
		_spec.SetField(workcondition.FieldLabel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Value(); ok {
		_spec.SetField(workcondition.FieldValue, field.TypeString, value)
	}
	if value, ok := _u.mutation.DisplayOrder(); ok {
		_spec.SetField(workcondition.FieldDisplayOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDisplayOrder(); ok {
		_spec.AddField(workcondition.FieldDisplayOrder, field.TypeInt, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{workcondition.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// WorkConditionUpdateOne is the builder for updating a single WorkCondition entity.
type WorkConditionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *WorkConditionMutation
}

// SetLabel sets the "label" field.
func (_u *WorkConditionUpdateOne) SetLabel(v string) *WorkConditionUpdateOne {
	_u.mutation.SetLabel(v)
	return _u
}

// SetNillableLabel sets the "label" field if the given value is not nil.
func (_u *WorkConditionUpdateOne) SetNillableLabel(v *string) *WorkConditionUpdateOne {
	if v != nil {
		_u.SetLabel(*v)
	}
	return _u
}

// SetValue sets the "value" field.
func (_u *WorkConditionUpdateOne) SetValue(v string) *WorkConditionUpdateOne {
	_u.mutation.SetValue(v)
	return _u
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (_u *WorkConditionUpdateOne) SetNillableValue(v *string) *WorkConditionUpdateOne {
	if v != nil {
		_u.SetValue(*v)
	}
	return _u
}

// SetDisplayOrder sets the "display_order" field.
func (_u *WorkConditionUpdateOne) SetDisplayOrder(v int) *WorkConditionUpdateOne {
	_u.mutation.ResetDisplayOrder()
	_u.mutation.SetDisplayOrder(v)
	return _u
}

// SetNillableDisplayOrder sets the "display_order" field if the given value is not nil.
func (_u *WorkConditionUpdateOne) SetNillableDisplayOrder(v *int) *WorkConditionUpdateOne {
	if v != nil {
		_u.SetDisplayOrder(*v)
	}
	return _u
}

// AddDisplayOrder adds value to the "display_order" field.
func (_u *WorkConditionUpdateOne) AddDisplayOrder(v int) *WorkConditionUpdateOne {
	_u.mutation.AddDisplayOrder(v)
	return _u
}

// Mutation returns the WorkConditionMutation object of the builder.
func (_u *WorkConditionUpdateOne) Mutation() *WorkConditionMutation {
	return _u.mutation
}

// Where appends a list predicates to the WorkConditionUpdate builder.
func (_u *WorkConditionUpdateOne) Where(ps ...predicate.WorkCondition) *WorkConditionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *WorkConditionUpdateOne) Select(field string, fields ...string) *WorkConditionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated WorkCondition entity.
func (_u *WorkConditionUpdateOne) Save(ctx context.Context) (*WorkCondition, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WorkConditionUpdateOne) SaveX(ctx context.Context) *WorkCondition {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *WorkConditionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WorkConditionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *WorkConditionUpdateOne) check() error {
	if v, ok := _u.mutation.Label(); ok {
		if err := workcondition.LabelValidator(v); err != nil {
			return &ValidationError{Name: "label", err: fmt.Errorf(`ent: validator failed for field "WorkCondition.label": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Value(); ok {
		if err := workcondition.ValueValidator(v); err != nil {
			return &ValidationError{Name: "value", err: fmt.Errorf(`ent: validator failed for field "WorkCondition.value": %w`, err)}
		}
	}
	return nil
}

func (_u *WorkConditionUpdateOne) sqlSave(ctx context.Context) (_node *WorkCondition, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(workcondition.Table, workcondition.Columns, sqlgraph.NewFieldSpec(workcondition.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "WorkCondition.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, workcondition.FieldID)
		for _, f := range fields {
			if !workcondition.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != workcondition.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Label(); ok {
		_spec.SetField(workcondition.FieldLabel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Value(); ok {
		_spec.SetField(workcondition.FieldValue, field.TypeString, value)
	}
	if value, ok := _u.mutation.DisplayOrder(); ok {
		_spec.SetField(workcondition.FieldDisplayOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDisplayOrder(); ok {
		_spec.AddField(workcondition.FieldDisplayOrder, field.TypeInt, value)
	}
	_node = &WorkCondition{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{workcondition.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
