// Code generated by ent, DO NOT EDIT.

package project

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the project type in the database.
	Label = "project"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldPeriodStart holds the string denoting the period_start field in the database.
	FieldPeriodStart = "period_start"
	// FieldPeriodEnd holds the string denoting the period_end field in the database.
	FieldPeriodEnd = "period_end"
	// FieldTeam holds the string denoting the team field in the database.
	FieldTeam = "team"
	// FieldRole holds the string denoting the role field in the database.
	FieldRole = "role"
	// FieldSummary holds the string denoting the summary field in the database.
	FieldSummary = "summary"
	// EdgeTechs holds the string denoting the techs edge name in mutations.
	EdgeTechs = "techs"
	// EdgePhases holds the string denoting the phases edge name in mutations.
	EdgePhases = "phases"
	// Table holds the table name of the project in the database.
	Table = "projects"
	// TechsTable is the table that holds the techs relation/edge. The primary key declared below.
	TechsTable = "project_techs"
	// TechsInverseTable is the table name for the Tech entity.
	// It exists in this package in order to avoid circular dependency with the "tech" package.
	TechsInverseTable = "techs"
	// PhasesTable is the table that holds the phases relation/edge. The primary key declared below.
	PhasesTable = "project_phases"
	// PhasesInverseTable is the table name for the Phase entity.
	// It exists in this package in order to avoid circular dependency with the "phase" package.
	PhasesInverseTable = "phases"
)

// Columns holds all SQL columns for project fields.
var Columns = []string{
	FieldID,
	FieldTitle,
	FieldPeriodStart,
	FieldPeriodEnd,
	FieldTeam,
	FieldRole,
	FieldSummary,
}

var (
	// TechsPrimaryKey and TechsColumn2 are the table columns denoting the
	// primary key for the techs relation (M2M).
	TechsPrimaryKey = []string{"project_id", "tech_id"}
	// PhasesPrimaryKey and PhasesColumn2 are the table columns denoting the
	// primary key for the phases relation (M2M).
	PhasesPrimaryKey = []string{"project_id", "phase_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// TitleValidator is a validator for the "title" field. It is called by the builders before save.
	TitleValidator func(string) error
	// TeamValidator is a validator for the "team" field. It is called by the builders before save.
	TeamValidator func(string) error
	// RoleValidator is a validator for the "role" field. It is called by the builders before save.
	RoleValidator func(string) error
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)

// OrderOption defines the ordering options for the Project queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTitle orders the results by the title field.
func ByTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitle, opts...).ToFunc()
}

// ByPeriodStart orders the results by the period_start field.
func ByPeriodStart(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPeriodStart, opts...).ToFunc()
}

// ByPeriodEnd orders the results by the period_end field.
func ByPeriodEnd(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPeriodEnd, opts...).ToFunc()
}

// ByTeam orders the results by the team field.
func ByTeam(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTeam, opts...).ToFunc()
}

// ByRole orders the results by the role field.
func ByRole(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRole, opts...).ToFunc()
}

// BySummary orders the results by the summary field.
func BySummary(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSummary, opts...).ToFunc()
}

// ByTechsCount orders the results by techs count.
func ByTechsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newTechsStep(), opts...)
	}
}

// ByTechs orders the results by techs terms.
func ByTechs(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTechsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByPhasesCount orders the results by phases count.
func ByPhasesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newPhasesStep(), opts...)
	}
}

// ByPhases orders the results by phases terms.
func ByPhases(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPhasesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newTechsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TechsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, false, TechsTable, TechsPrimaryKey...),
	)
}
func newPhasesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PhasesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, false, PhasesTable, PhasesPrimaryKey...),
	)
}
