// Code generated by ent, DO NOT EDIT.

package settings

import (
	"entgo.io/ent/dialect/sql"
	"github.com/hashiguchip/chokunavi/apps/api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Settings {
	return predicate.Settings(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Settings {
	return predicate.Settings(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Settings {
	return predicate.Settings(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Settings {
	return predicate.Settings(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Settings {
	return predicate.Settings(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Settings {
	return predicate.Settings(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Settings {
	return predicate.Settings(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Settings {
	return predicate.Settings(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Settings {
	return predicate.Settings(sql.FieldLTE(FieldID, id))
}

// AvailableFrom applies equality check predicate on the "available_from" field. It's identical to AvailableFromEQ.
func AvailableFrom(v string) predicate.Settings {
	return predicate.Settings(sql.FieldEQ(FieldAvailableFrom, v))
}

// WorkHours applies equality check predicate on the "work_hours" field. It's identical to WorkHoursEQ.
func WorkHours(v string) predicate.Settings {
	return predicate.Settings(sql.FieldEQ(FieldWorkHours, v))
}

// ContractType applies equality check predicate on the "contract_type" field. It's identical to ContractTypeEQ.
func ContractType(v string) predicate.Settings {
	return predicate.Settings(sql.FieldEQ(FieldContractType, v))
}

// Communication applies equality check predicate on the "communication" field. It's identical to CommunicationEQ.
func Communication(v string) predicate.Settings {
	return predicate.Settings(sql.FieldEQ(FieldCommunication, v))
}

// InvoiceStatus applies equality check predicate on the "invoice_status" field. It's identical to InvoiceStatusEQ.
func InvoiceStatus(v string) predicate.Settings {
	return predicate.Settings(sql.FieldEQ(FieldInvoiceStatus, v))
}

// XProfileURL applies equality check predicate on the "x_profile_url" field. It's identical to XProfileURLEQ.
func XProfileURL(v string) predicate.Settings {
	return predicate.Settings(sql.FieldEQ(FieldXProfileURL, v))
}

// XPostURL applies equality check predicate on the "x_post_url" field. It's identical to XPostURLEQ.
func XPostURL(v string) predicate.Settings {
	return predicate.Settings(sql.FieldEQ(FieldXPostURL, v))
}

// XPostText applies equality check predicate on the "x_post_text" field. It's identical to XPostTextEQ.
func XPostText(v string) predicate.Settings {
	return predicate.Settings(sql.FieldEQ(FieldXPostText, v))
}

// AvailableFromEQ applies the EQ predicate on the "available_from" field.
func AvailableFromEQ(v string) predicate.Settings {
	return predicate.Settings(sql.FieldEQ(FieldAvailableFrom, v))
}

// AvailableFromNEQ applies the NEQ predicate on the "available_from" field.
func AvailableFromNEQ(v string) predicate.Settings {
	return predicate.Settings(sql.FieldNEQ(FieldAvailableFrom, v))
}

// AvailableFromIn applies the In predicate on the "available_from" field.
func AvailableFromIn(vs ...string) predicate.Settings {
	return predicate.Settings(sql.FieldIn(FieldAvailableFrom, vs...))
}

// AvailableFromNotIn applies the NotIn predicate on the "available_from" field.
func AvailableFromNotIn(vs ...string) predicate.Settings {
	return predicate.Settings(sql.FieldNotIn(FieldAvailableFrom, vs...))
}

// AvailableFromGT applies the GT predicate on the "available_from" field.
func AvailableFromGT(v string) predicate.Settings {
	return predicate.Settings(sql.FieldGT(FieldAvailableFrom, v))
}

// AvailableFromGTE applies the GTE predicate on the "available_from" field.
func AvailableFromGTE(v string) predicate.Settings {
	return predicate.Settings(sql.FieldGTE(FieldAvailableFrom, v))
}

// AvailableFromLT applies the LT predicate on the "available_from" field.
func AvailableFromLT(v string) predicate.Settings {
	return predicate.Settings(sql.FieldLT(FieldAvailableFrom, v))
}

// AvailableFromLTE applies the LTE predicate on the "available_from" field.
func AvailableFromLTE(v string) predicate.Settings {
	return predicate.Settings(sql.FieldLTE(FieldAvailableFrom, v))
}

// AvailableFromContains applies the Contains predicate on the "available_from" field.
func AvailableFromContains(v string) predicate.Settings {
	return predicate.Settings(sql.FieldContains(FieldAvailableFrom, v))
}

// AvailableFromHasPrefix applies the HasPrefix predicate on the "available_from" field.
func AvailableFromHasPrefix(v string) predicate.Settings {
	return predicate.Settings(sql.FieldHasPrefix(FieldAvailableFrom, v))
}

// AvailableFromHasSuffix applies the HasSuffix predicate on the "available_from" field.
func AvailableFromHasSuffix(v string) predicate.Settings {
	return predicate.Settings(sql.FieldHasSuffix(FieldAvailableFrom, v))
}

// AvailableFromEqualFold applies the EqualFold predicate on the "available_from" field.
func AvailableFromEqualFold(v string) predicate.Settings {
	return predicate.Settings(sql.FieldEqualFold(FieldAvailableFrom, v))
}

// AvailableFromContainsFold applies the ContainsFold predicate on the "available_from" field.
func AvailableFromContainsFold(v string) predicate.Settings {
	return predicate.Settings(sql.FieldContainsFold(FieldAvailableFrom, v))
}

// WorkHoursEQ applies the EQ predicate on the "work_hours" field.
func WorkHoursEQ(v string) predicate.Settings {
	return predicate.Settings(sql.FieldEQ(FieldWorkHours, v))
}

// WorkHoursNEQ applies the NEQ predicate on the "work_hours" field.
func WorkHoursNEQ(v string) predicate.Settings {
	return predicate.Settings(sql.FieldNEQ(FieldWorkHours, v))
}

// WorkHoursIn applies the In predicate on the "work_hours" field.
func WorkHoursIn(vs ...string) predicate.Settings {
	return predicate.Settings(sql.FieldIn(FieldWorkHours, vs...))
}

// WorkHoursNotIn applies the NotIn predicate on the "work_hours" field.
func WorkHoursNotIn(vs ...string) predicate.Settings {
	return predicate.Settings(sql.FieldNotIn(FieldWorkHours, vs...))
}

// WorkHoursGT applies the GT predicate on the "work_hours" field.
func WorkHoursGT(v string) predicate.Settings {
	return predicate.Settings(sql.FieldGT(FieldWorkHours, v))
}

// WorkHoursGTE applies the GTE predicate on the "work_hours" field.
func WorkHoursGTE(v string) predicate.Settings {
	return predicate.Settings(sql.FieldGTE(FieldWorkHours, v))
}

// WorkHoursLT applies the LT predicate on the "work_hours" field.
func WorkHoursLT(v string) predicate.Settings {
	return predicate.Settings(sql.FieldLT(FieldWorkHours, v))
}

// WorkHoursLTE applies the LTE predicate on the "work_hours" field.
func WorkHoursLTE(v string) predicate.Settings {
	return predicate.Settings(sql.FieldLTE(FieldWorkHours, v))
}

// WorkHoursContains applies the Contains predicate on the "work_hours" field.
func WorkHoursContains(v string) predicate.Settings {
	return predicate.Settings(sql.FieldContains(FieldWorkHours, v))
}

// WorkHoursHasPrefix applies the HasPrefix predicate on the "work_hours" field.
func WorkHoursHasPrefix(v string) predicate.Settings {
	return predicate.Settings(sql.FieldHasPrefix(FieldWorkHours, v))
}

// WorkHoursHasSuffix applies the HasSuffix predicate on the "work_hours" field.
func WorkHoursHasSuffix(v string) predicate.Settings {
	return predicate.Settings(sql.FieldHasSuffix(FieldWorkHours, v))
}

// WorkHoursEqualFold applies the EqualFold predicate on the "work_hours" field.
func WorkHoursEqualFold(v string) predicate.Settings {
	return predicate.Settings(sql.FieldEqualFold(FieldWorkHours, v))
}

// WorkHoursContainsFold applies the ContainsFold predicate on the "work_hours" field.
func WorkHoursContainsFold(v string) predicate.Settings {
	return predicate.Settings(sql.FieldContainsFold(FieldWorkHours, v))
}

// ContractTypeEQ applies the EQ predicate on the "contract_type" field.
func ContractTypeEQ(v string) predicate.Settings {
	return predicate.Settings(sql.FieldEQ(FieldContractType, v))
}

// ContractTypeNEQ applies the NEQ predicate on the "contract_type" field.
func ContractTypeNEQ(v string) predicate.Settings {
	return predicate.Settings(sql.FieldNEQ(FieldContractType, v))
}

// ContractTypeIn applies the In predicate on the "contract_type" field.
func ContractTypeIn(vs ...string) predicate.Settings {
	return predicate.Settings(sql.FieldIn(FieldContractType, vs...))
}

// ContractTypeNotIn applies the NotIn predicate on the "contract_type" field.
func ContractTypeNotIn(vs ...string) predicate.Settings {
	return predicate.Settings(sql.FieldNotIn(FieldContractType, vs...))
}

// ContractTypeGT applies the GT predicate on the "contract_type" field.
func ContractTypeGT(v string) predicate.Settings {
	return predicate.Settings(sql.FieldGT(FieldContractType, v))
}

// ContractTypeGTE applies the GTE predicate on the "contract_type" field.
func ContractTypeGTE(v string) predicate.Settings {
	return predicate.Settings(sql.FieldGTE(FieldContractType, v))
}

// ContractTypeLT applies the LT predicate on the "contract_type" field.
func ContractTypeLT(v string) predicate.Settings {
	return predicate.Settings(sql.FieldLT(FieldContractType, v))
}

// ContractTypeLTE applies the LTE predicate on the "contract_type" field.
func ContractTypeLTE(v string) predicate.Settings {
	return predicate.Settings(sql.FieldLTE(FieldContractType, v))
}

// ContractTypeContains applies the Contains predicate on the "contract_type" field.
func ContractTypeContains(v string) predicate.Settings {
	return predicate.Settings(sql.FieldContains(FieldContractType, v))
}

// ContractTypeHasPrefix applies the HasPrefix predicate on the "contract_type" field.
func ContractTypeHasPrefix(v string) predicate.Settings {
	return predicate.Settings(sql.FieldHasPrefix(FieldContractType, v))
}

// ContractTypeHasSuffix applies the HasSuffix predicate on the "contract_type" field.
func ContractTypeHasSuffix(v string) predicate.Settings {
	return predicate.Settings(sql.FieldHasSuffix(FieldContractType, v))
}

// ContractTypeEqualFold applies the EqualFold predicate on the "contract_type" field.
func ContractTypeEqualFold(v string) predicate.Settings {
	return predicate.Settings(sql.FieldEqualFold(FieldContractType, v))
}

// ContractTypeContainsFold applies the ContainsFold predicate on the "contract_type" field.
func ContractTypeContainsFold(v string) predicate.Settings {
	return predicate.Settings(sql.FieldContainsFold(FieldContractType, v))
}

// CommunicationEQ applies the EQ predicate on the "communication" field.
func CommunicationEQ(v string) predicate.Settings {
	return predicate.Settings(sql.FieldEQ(FieldCommunication, v))
}

// CommunicationNEQ applies the NEQ predicate on the "communication" field.
func CommunicationNEQ(v string) predicate.Settings {
	return predicate.Settings(sql.FieldNEQ(FieldCommunication, v))
}

// CommunicationIn applies the In predicate on the "communication" field.
func CommunicationIn(vs ...string) predicate.Settings {
	return predicate.Settings(sql.FieldIn(FieldCommunication, vs...))
}

// CommunicationNotIn applies the NotIn predicate on the "communication" field.
func CommunicationNotIn(vs ...string) predicate.Settings {
	return predicate.Settings(sql.FieldNotIn(FieldCommunication, vs...))
}

// CommunicationGT applies the GT predicate on the "communication" field.
func CommunicationGT(v string) predicate.Settings {
	return predicate.Settings(sql.FieldGT(FieldCommunication, v))
}

// CommunicationGTE applies the GTE predicate on the "communication" field.
func CommunicationGTE(v string) predicate.Settings {
	return predicate.Settings(sql.FieldGTE(FieldCommunication, v))
}

// CommunicationLT applies the LT predicate on the "communication" field.
func CommunicationLT(v string) predicate.Settings {
	return predicate.Settings(sql.FieldLT(FieldCommunication, v))
}

// CommunicationLTE applies the LTE predicate on the "communication" field.
func CommunicationLTE(v string) predicate.Settings {
	return predicate.Settings(sql.FieldLTE(FieldCommunication, v))
}

// CommunicationContains applies the Contains predicate on the "communication" field.
func CommunicationContains(v string) predicate.Settings {
	return predicate.Settings(sql.FieldContains(FieldCommunication, v))
}

// CommunicationHasPrefix applies the HasPrefix predicate on the "communication" field.
func CommunicationHasPrefix(v string) predicate.Settings {
	return predicate.Settings(sql.FieldHasPrefix(FieldCommunication, v))
}

// CommunicationHasSuffix applies the HasSuffix predicate on the "communication" field.
func CommunicationHasSuffix(v string) predicate.Settings {
	return predicate.Settings(sql.FieldHasSuffix(FieldCommunication, v))
}

// CommunicationEqualFold applies the EqualFold predicate on the "communication" field.
func CommunicationEqualFold(v string) predicate.Settings {
	return predicate.Settings(sql.FieldEqualFold(FieldCommunication, v))
}

// CommunicationContainsFold applies the ContainsFold predicate on the "communication" field.
func CommunicationContainsFold(v string) predicate.Settings {
	return predicate.Settings(sql.FieldContainsFold(FieldCommunication, v))
}

// InvoiceStatusEQ applies the EQ predicate on the "invoice_status" field.
func InvoiceStatusEQ(v string) predicate.Settings {
	return predicate.Settings(sql.FieldEQ(FieldInvoiceStatus, v))
}

// InvoiceStatusNEQ applies the NEQ predicate on the "invoice_status" field.
func InvoiceStatusNEQ(v string) predicate.Settings {
	return predicate.Settings(sql.FieldNEQ(FieldInvoiceStatus, v))
}

// InvoiceStatusIn applies the In predicate on the "invoice_status" field.
func InvoiceStatusIn(vs ...string) predicate.Settings {
	return predicate.Settings(sql.FieldIn(FieldInvoiceStatus, vs...))
}

// InvoiceStatusNotIn applies the NotIn predicate on the "invoice_status" field.
func InvoiceStatusNotIn(vs ...string) predicate.Settings {
	return predicate.Settings(sql.FieldNotIn(FieldInvoiceStatus, vs...))
}

// InvoiceStatusGT applies the GT predicate on the "invoice_status" field.
func InvoiceStatusGT(v string) predicate.Settings {
	return predicate.Settings(sql.FieldGT(FieldInvoiceStatus, v))
}

// InvoiceStatusGTE applies the GTE predicate on the "invoice_status" field.
func InvoiceStatusGTE(v string) predicate.Settings {
	return predicate.Settings(sql.FieldGTE(FieldInvoiceStatus, v))
}

// InvoiceStatusLT applies the LT predicate on the "invoice_status" field.
func InvoiceStatusLT(v string) predicate.Settings {
	return predicate.Settings(sql.FieldLT(FieldInvoiceStatus, v))
}

// InvoiceStatusLTE applies the LTE predicate on the "invoice_status" field.
func InvoiceStatusLTE(v string) predicate.Settings {
	return predicate.Settings(sql.FieldLTE(FieldInvoiceStatus, v))
}

// InvoiceStatusContains applies the Contains predicate on the "invoice_status" field.
func InvoiceStatusContains(v string) predicate.Settings {
	return predicate.Settings(sql.FieldContains(FieldInvoiceStatus, v))
}

// InvoiceStatusHasPrefix applies the HasPrefix predicate on the "invoice_status" field.
func InvoiceStatusHasPrefix(v string) predicate.Settings {
	return predicate.Settings(sql.FieldHasPrefix(FieldInvoiceStatus, v))
}

// InvoiceStatusHasSuffix applies the HasSuffix predicate on the "invoice_status" field.
func InvoiceStatusHasSuffix(v string) predicate.Settings {
	return predicate.Settings(sql.FieldHasSuffix(FieldInvoiceStatus, v))
}

// InvoiceStatusEqualFold applies the EqualFold predicate on the "invoice_status" field.
func InvoiceStatusEqualFold(v string) predicate.Settings {
	return predicate.Settings(sql.FieldEqualFold(FieldInvoiceStatus, v))
}

// InvoiceStatusContainsFold applies the ContainsFold predicate on the "invoice_status" field.
func InvoiceStatusContainsFold(v string) predicate.Settings {
	return predicate.Settings(sql.FieldContainsFold(FieldInvoiceStatus, v))
}

// XProfileURLEQ applies the EQ predicate on the "x_profile_url" field.
func XProfileURLEQ(v string) predicate.Settings {
	return predicate.Settings(sql.FieldEQ(FieldXProfileURL, v))
}

// XProfileURLNEQ applies the NEQ predicate on the "x_profile_url" field.
func XProfileURLNEQ(v string) predicate.Settings {
	return predicate.Settings(sql.FieldNEQ(FieldXProfileURL, v))
}

// XProfileURLIn applies the In predicate on the "x_profile_url" field.
func XProfileURLIn(vs ...string) predicate.Settings {
	return predicate.Settings(sql.FieldIn(FieldXProfileURL, vs...))
}

// XProfileURLNotIn applies the NotIn predicate on the "x_profile_url" field.
func XProfileURLNotIn(vs ...string) predicate.Settings {
	return predicate.Settings(sql.FieldNotIn(FieldXProfileURL, vs...))
}

// XProfileURLGT applies the GT predicate on the "x_profile_url" field.
func XProfileURLGT(v string) predicate.Settings {
	return predicate.Settings(sql.FieldGT(FieldXProfileURL, v))
}

// XProfileURLGTE applies the GTE predicate on the "x_profile_url" field.
func XProfileURLGTE(v string) predicate.Settings {
	return predicate.Settings(sql.FieldGTE(FieldXProfileURL, v))
}

// XProfileURLLT applies the LT predicate on the "x_profile_url" field.
func XProfileURLLT(v string) predicate.Settings {
	return predicate.Settings(sql.FieldLT(FieldXProfileURL, v))
}

// XProfileURLLTE applies the LTE predicate on the "x_profile_url" field.
func XProfileURLLTE(v string) predicate.Settings {
	return predicate.Settings(sql.FieldLTE(FieldXProfileURL, v))
}

// XProfileURLContains applies the Contains predicate on the "x_profile_url" field.
func XProfileURLContains(v string) predicate.Settings {
	return predicate.Settings(sql.FieldContains(FieldXProfileURL, v))
}

// XProfileURLHasPrefix applies the HasPrefix predicate on the "x_profile_url" field.
func XProfileURLHasPrefix(v string) predicate.Settings {
	return predicate.Settings(sql.FieldHasPrefix(FieldXProfileURL, v))
}

// XProfileURLHasSuffix applies the HasSuffix predicate on the "x_profile_url" field.
func XProfileURLHasSuffix(v string) predicate.Settings {
	return predicate.Settings(sql.FieldHasSuffix(FieldXProfileURL, v))
}

// XProfileURLIsNil applies the IsNil predicate on the "x_profile_url" field.
func XProfileURLIsNil() predicate.Settings {
	return predicate.Settings(sql.FieldIsNull(FieldXProfileURL))
}

// XProfileURLNotNil applies the NotNil predicate on the "x_profile_url" field.
func XProfileURLNotNil() predicate.Settings {
	return predicate.Settings(sql.FieldNotNull(FieldXProfileURL))
}

// XProfileURLEqualFold applies the EqualFold predicate on the "x_profile_url" field.
func XProfileURLEqualFold(v string) predicate.Settings {
	return predicate.Settings(sql.FieldEqualFold(FieldXProfileURL, v))
}

// XProfileURLContainsFold applies the ContainsFold predicate on the "x_profile_url" field.
func XProfileURLContainsFold(v string) predicate.Settings {
	return predicate.Settings(sql.FieldContainsFold(FieldXProfileURL, v))
}

// XPostURLEQ applies the EQ predicate on the "x_post_url" field.
func XPostURLEQ(v string) predicate.Settings {
	return predicate.Settings(sql.FieldEQ(FieldXPostURL, v))
}

// XPostURLNEQ applies the NEQ predicate on the "x_post_url" field.
func XPostURLNEQ(v string) predicate.Settings {
	return predicate.Settings(sql.FieldNEQ(FieldXPostURL, v))
}

// XPostURLIn applies the In predicate on the "x_post_url" field.
func XPostURLIn(vs ...string) predicate.Settings {
	return predicate.Settings(sql.FieldIn(FieldXPostURL, vs...))
}

// XPostURLNotIn applies the NotIn predicate on the "x_post_url" field.
func XPostURLNotIn(vs ...string) predicate.Settings {
	return predicate.Settings(sql.FieldNotIn(FieldXPostURL, vs...))
}

// XPostURLGT applies the GT predicate on the "x_post_url" field.
func XPostURLGT(v string) predicate.Settings {
	return predicate.Settings(sql.FieldGT(FieldXPostURL, v))
}

// XPostURLGTE applies the GTE predicate on the "x_post_url" field.
func XPostURLGTE(v string) predicate.Settings {
	return predicate.Settings(sql.FieldGTE(FieldXPostURL, v))
}

// XPostURLLT applies the LT predicate on the "x_post_url" field.
func XPostURLLT(v string) predicate.Settings {
	return predicate.Settings(sql.FieldLT(FieldXPostURL, v))
}

// XPostURLLTE applies the LTE predicate on the "x_post_url" field.
func XPostURLLTE(v string) predicate.Settings {
	return predicate.Settings(sql.FieldLTE(FieldXPostURL, v))
}

// XPostURLContains applies the Contains predicate on the "x_post_url" field.
func XPostURLContains(v string) predicate.Settings {
	return predicate.Settings(sql.FieldContains(FieldXPostURL, v))
}

// XPostURLHasPrefix applies the HasPrefix predicate on the "x_post_url" field.
func XPostURLHasPrefix(v string) predicate.Settings {
	return predicate.Settings(sql.FieldHasPrefix(FieldXPostURL, v))
}

// XPostURLHasSuffix applies the HasSuffix predicate on the "x_post_url" field.
func XPostURLHasSuffix(v string) predicate.Settings {
	return predicate.Settings(sql.FieldHasSuffix(FieldXPostURL, v))
}

// XPostURLIsNil applies the IsNil predicate on the "x_post_url" field.
func XPostURLIsNil() predicate.Settings {
	return predicate.Settings(sql.FieldIsNull(FieldXPostURL))
}

// XPostURLNotNil applies the NotNil predicate on the "x_post_url" field.
func XPostURLNotNil() predicate.Settings {
	return predicate.Settings(sql.FieldNotNull(FieldXPostURL))
}

// XPostURLEqualFold applies the EqualFold predicate on the "x_post_url" field.
func XPostURLEqualFold(v string) predicate.Settings {
	return predicate.Settings(sql.FieldEqualFold(FieldXPostURL, v))
}

// XPostURLContainsFold applies the ContainsFold predicate on the "x_post_url" field.
func XPostURLContainsFold(v string) predicate.Settings {
	return predicate.Settings(sql.FieldContainsFold(FieldXPostURL, v))
}

// XPostTextEQ applies the EQ predicate on the "x_post_text" field.
func XPostTextEQ(v string) predicate.Settings {
	return predicate.Settings(sql.FieldEQ(FieldXPostText, v))
}

// XPostTextNEQ applies the NEQ predicate on the "x_post_text" field.
func XPostTextNEQ(v string) predicate.Settings {
	return predicate.Settings(sql.FieldNEQ(FieldXPostText, v))
}

// XPostTextIn applies the In predicate on the "x_post_text" field.
func XPostTextIn(vs ...string) predicate.Settings {
	return predicate.Settings(sql.FieldIn(FieldXPostText, vs...))
}

// XPostTextNotIn applies the NotIn predicate on the "x_post_text" field.
func XPostTextNotIn(vs ...string) predicate.Settings {
	return predicate.Settings(sql.FieldNotIn(FieldXPostText, vs...))
}

// XPostTextGT applies the GT predicate on the "x_post_text" field.
func XPostTextGT(v string) predicate.Settings {
	return predicate.Settings(sql.FieldGT(FieldXPostText, v))
}

// XPostTextGTE applies the GTE predicate on the "x_post_text" field.
func XPostTextGTE(v string) predicate.Settings {
	return predicate.Settings(sql.FieldGTE(FieldXPostText, v))
}

// XPostTextLT applies the LT predicate on the "x_post_text" field.
func XPostTextLT(v string) predicate.Settings {
	return predicate.Settings(sql.FieldLT(FieldXPostText, v))
}

// XPostTextLTE applies the LTE predicate on the "x_post_text" field.
func XPostTextLTE(v string) predicate.Settings {
	return predicate.Settings(sql.FieldLTE(FieldXPostText, v))
}

// XPostTextContains applies the Contains predicate on the "x_post_text" field.
func XPostTextContains(v string) predicate.Settings {
	return predicate.Settings(sql.FieldContains(FieldXPostText, v))
}

// XPostTextHasPrefix applies the HasPrefix predicate on the "x_post_text" field.
func XPostTextHasPrefix(v string) predicate.Settings {
	return predicate.Settings(sql.FieldHasPrefix(FieldXPostText, v))
}

// XPostTextHasSuffix applies the HasSuffix predicate on the "x_post_text" field.
func XPostTextHasSuffix(v string) predicate.Settings {
	return predicate.Settings(sql.FieldHasSuffix(FieldXPostText, v))
}

// XPostTextIsNil applies the IsNil predicate on the "x_post_text" field.
func XPostTextIsNil() predicate.Settings {
	return predicate.Settings(sql.FieldIsNull(FieldXPostText))
}

// XPostTextNotNil applies the NotNil predicate on the "x_post_text" field.
func XPostTextNotNil() predicate.Settings {
	return predicate.Settings(sql.FieldNotNull(FieldXPostText))
}

// XPostTextEqualFold applies the EqualFold predicate on the "x_post_text" field.
func XPostTextEqualFold(v string) predicate.Settings {
	return predicate.Settings(sql.FieldEqualFold(FieldXPostText, v))
}

// XPostTextContainsFold applies the ContainsFold predicate on the "x_post_text" field.
func XPostTextContainsFold(v string) predicate.Settings {
	return predicate.Settings(sql.FieldContainsFold(FieldXPostText, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Settings) predicate.Settings {
	return predicate.Settings(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Settings) predicate.Settings {
	return predicate.Settings(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Settings) predicate.Settings {
	return predicate.Settings(sql.NotPredicates(p))
}
