// Code generated by ent, DO NOT EDIT.

package faqitem

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the faqitem type in the database.
	Label = "faq_item"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldQuestion holds the string denoting the question field in the database.
	FieldQuestion = "question"
	// FieldAnswer holds the string denoting the answer field in the database.
	FieldAnswer = "answer"
	// FieldDisplayOrder holds the string denoting the display_order field in the database.
	FieldDisplayOrder = "display_order"
	// Table holds the table name of the faqitem in the database.
	Table = "faq_items"
)

// Columns holds all SQL columns for faqitem fields.
var Columns = []string{
	FieldID,
	FieldQuestion,
	FieldAnswer,
	FieldDisplayOrder,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// QuestionValidator is a validator for the "question" field. It is called by the builders before save.
	QuestionValidator func(string) error
	// AnswerValidator is a validator for the "answer" field. It is called by the builders before save.
	AnswerValidator func(string) error
	// DefaultDisplayOrder holds the default value on creation for the "display_order" field.
	DefaultDisplayOrder int
)

// OrderOption defines the ordering options for the FAQItem queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByQuestion orders the results by the question field.
func ByQuestion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQuestion, opts...).ToFunc()
}

// ByAnswer orders the results by the answer field.
func ByAnswer(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAnswer, opts...).ToFunc()
}

// ByDisplayOrder orders the results by the display_order field.
func ByDisplayOrder(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDisplayOrder, opts...).ToFunc()
}
